Authentication System Revamp - Login/Register setup moved to Popups
CircuitVerse/CircuitVerse pull request #1602
Opened 2020-08-16 16:28 UTC by aayush-05

![image](https://user-images.githubusercontent.com/47032027/90339032-a2464e00-e00b-11ea-9d0e-3dc33692bb86.png)

2020-08-16 19:52 UTC, aayush-05 commented
Fixed all the major codeclimate issues. The ones involving id selectors (preferred to be used here), use of instance variables in helpers and tests can be ignored

2020-08-18 03:57 UTC, tachyons commented
Build is failing

2020-08-18 04:23 UTC, aayush-05 commented
Yeah, I am not able to figure out why though. Capybara is unable to find the "Log In" link, even when its right there in the Navbar.
![image](https://user-images.githubusercontent.com/47032027/90470242-97d5a280-e138-11ea-83f5-c92a7cc0493b.png)
Can you check once on why this is happening?

2020-08-18 16:32 UTC, nitin10s requested changes
Extra margin needed at the bottom of the social logins, also the modal looks quite close to the top and could be shifted down

This is not working in sync with simulator.. why so?

The password reset screen looks quite odd, maybe we can remove the illustration and keep the content in centre? Whatsay?

2020-08-18 16:32 UTC, nitin10s commented on app/views/users/sessions/_popup_login.html.erb
> +    <div class="modal-content">
.modal-content require a border: 0 to remove that slight extra white space at the bottom

2020-08-20 12:33 UTC, satu0king commented on config/routes.rb
> +  get "users/sign_up" => redirect('/')
Does this line need to be repeated twice?

2020-08-20 12:36 UTC, satu0king commented
Looks good but the following scenario didn't work very well
1) I log out
2) Go to simulator page
3) Make a circuit and save
4) It just redirects to home page (Not prompting login)

This is step down from the current setup which redirects to a login page.

2026-05-25 10:50 UTC, Me-Priyank commented
@Nihal4777  Closing as superseded.

This was fully solved during GSoC 2023 through a better architectural approach:

- #3862 - JWT implementation: RSA-256 signed tokens stored in a cvt cookie (same_site: strict, secure in production) with a 
  custom Warden strategy for API authentication & New API endpoints (/api/v1/me, /api/v1/projects, /api/v1/projects/:id/check_edit_access) backed by JWT auth.
- CircuitVerse/cv-frontend-vue#170 - Simulator wired up to use JWT: simulatorHandler.vue reads the cvt cookie authenticates via API, and saves circuit data to localStorage before any redirect so no work is lost.

A Bootstrap modal wrapping a Devise HTML form (what this PR proposed) is no longer the right approach, the simulator is a decoupled Vue SPA that talks to Rails exclusively via JWT-authenticated API calls, never via HTML forms.

2026-05-25 10:50 UTC, closed without merging