button is added to create new circuit direct from subcircuit dialog b…
CircuitVerse/CircuitVerse pull request #1787
Opened 2020-10-04 16:11 UTC by GAUTAMSAHARAN

Fixes #1751

2020-10-04 16:13 UTC, GAUTAMSAHARAN commented
![Uploading Screenshot from 2020-10-04 17-48-46.png…]()

2020-10-04 16:15 UTC, GAUTAMSAHARAN commented
![Screenshot from 2020-10-04 17-48-46](https://user-images.githubusercontent.com/54721472/95020790-e9a39f00-068a-11eb-83dd-01c2ee9ac168.png)

2020-10-08 14:33 UTC, abstrekt commented on public/css/main.stylesheet.css
> +  padding: 10px 17px !important;
Why is this necessary?

2020-10-08 14:35 UTC, abstrekt requested changes
Avoid inline style,
is it not possible to do with a single div? instead of having a nonEmpty and an empty Div?
Also, have the same button style as the insertSubcircuit button
Use proper HTML breaks instead of having one long line of HTML
After creating a new circuit through the new circuit button, update the div with the appropriate options.

2020-11-18 12:57 UTC, satu0king commented on app/views/simulator/edit.html.erb
> +><div id="subCircuitNonEmptyDiaglog" style="height: fit-content;"></div><div id="subCircuitEmptyDialog"><span><p>Looks like there are no other circuits which doesn't have this circuit as a dependency
Creating a new dialog for nonEmpty and Empty is over kill. Please use old dialog itself.

2023-02-18 03:12 UTC, tachyons commented
Closing due to inactivity

2023-02-18 03:12 UTC, closed without merging