Added option to directly edit the project title from header
CircuitVerse/CircuitVerse pull request #1883
Opened 2020-11-06 05:23 UTC by dipanshparmar

Fixes #1808 

#### Describe the changes you have made in this PR -
1. Added option to directly edit the project title from the header itself.

### Screenshots of the changes (If any) -
**Initial State**
![image](https://user-images.githubusercontent.com/49204837/98329037-404f2080-201d-11eb-8063-226f1436f4b8.png)

**On Change**
(Changes are synced automatically between both of the project title inputs)
![image](https://user-images.githubusercontent.com/49204837/98329250-ca978480-201d-11eb-83ca-81ac4f9e25c2.png)

2020-11-20 10:15 UTC, satu0king commented on public/src/ux.js
> +const watchOneInputChangeAndUpdateAnother = (objectToListen, objectToChange) => $(`${objectToListen}`).on('input', (e) => { $(`${objectToChange}`).val(e.target.value); });
Neat!

2020-11-20 10:17 UTC, satu0king requested changes
Works nicely but please fix conflicts and the changes requested.

2020-11-20 10:17 UTC, satu0king commented on public/src/ux.js
> +    watchOneInputChangeAndUpdateAnother('.projectName', '[name="setProjectName"]'); // setting the value of sidebar title on header title change
You actually made a mistake. The name of the project itself is not changing, only the UI is changing, please fix this.

2020-11-20 10:17 UTC, satu0king commented on public/src/listeners.js
> +        }
I think this is a mistake, please remove this.

2020-11-20 12:30 UTC, dipanshparmar commented
> Works nicely but please fix conflicts and the changes requested.

@satu0king working on this!

2020-11-20 16:15 UTC, dipanshparmar commented
@satu0king please have a look now.

2020-11-24 10:49 UTC, dipanshparmar commented
@satu0king closing the PR as it is related to new_UI branch and making a new one for master.

2020-11-24 10:49 UTC, closed without merging