signup form validation
CircuitVerse/CircuitVerse pull request #1948
Opened 2020-11-21 15:12 UTC by pavanjoshi914

closes #1640 ,closes #1503 ,closes #1633 ,closes #1649 

#### Describe the changes you have made in this PR -

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2020-11-22 16:09 UTC, pavanjoshi914 commented on spec/system/signup_spec.rb
> +  it "should not signup when username is invalid" do
Not necessary making test describe in sync with others

2020-12-03 02:33 UTC, pavanjoshi914 commented
@satu0king @tachyons  please have a review on this!!

2021-03-21 14:50 UTC, satu0king commented on spec/system/signup_spec.rb
> -  end
Why is this test removed?

2021-03-21 14:51 UTC, satu0king requested changes

2021-03-21 14:51 UTC, satu0king commented on app/models/user.rb
> +  validates :name, format: { with: /\A[a-zA-Z ]{3,36}\z/,
New tests are needed to test if this functionality works as expected.

2021-11-06 03:36 UTC, closed without merging