New Feature buzzer
CircuitVerse/CircuitVerse pull request #2046
Opened 2020-12-16 20:47 UTC by mayank-kabra2001

Fixes #

#### Describe the changes you have made in this PR -

Created a new feature of buzzer - 

Inputs are frequency of the sound , duration upto which sound is played , and a play button . 
eg . input of 426 as frequency and 2 as duration and 1 as play will produce a C chord(426 Hz) for 2sec if play input is 1.

In properties its volume can be adjusted .
Also whether we want that frequency (eg. C chord) to be sharp or flat (i.e. C# or C') can be controlled by a checkbox .  

### Screenshots of the changes (If any) -

![Screenshot from 2020-12-17 02-09-28](https://user-images.githubusercontent.com/57330493/102403988-1837e180-400d-11eb-9a18-0e3d5f502006.png)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-02-28 17:25 UTC, abstrekt commented on public/src/ux.js
> +            $('#modulePropshowPropertieserty').hide();
is this a mistake?

2021-02-28 17:27 UTC, abstrekt commented on public/src/moduleSetup.js
> +import Diode from './modules/Diode' ;
trouble with webpacker due to this import. might have mixed code with #2045 ?

2021-02-28 17:39 UTC, abstrekt requested changes
I was testing this feature out, there some to be some unrelated codes maybe relating to PR #2045, I'm not sure if this feature is working as it suppose to in a normal use case but there is a bug where the buzzer won't stop -- to reproduce try playing the buzzer without providing any input in for the duration.

Seems like a great feature --would love to see this through, can you fix the above mention issues so that @satu0king can review it to be working properly?

2022-07-01 06:29 UTC, gr455 commented
This PR still needs work. A bunch of bugs with this one

2023-02-18 03:14 UTC, tachyons commented
Closing due to inactivity, feel free to re-open once the issues are addressed

2023-02-18 03:14 UTC, closed without merging