added friendly_id
CircuitVerse/CircuitVerse pull request #2059
Opened 2021-01-03 16:56 UTC by SingingApple

Fixes #2055 

#### Describe the changes you have made in this PR -
Added friendly_id for users model. 

### Screenshots of the changes (If any) -

![Screenshot from 2021-01-03 01-00-30](https://user-images.githubusercontent.com/39864404/103484150-96b8bf80-4e12-11eb-927f-af1671382de4.png)

2021-01-14 17:38 UTC, gr455 requested changes
There seem to be multiple tests failing. Some tets may reqiuire changes due to introduction of friendly id for them to pass

2021-02-27 12:10 UTC, apurv-1 approved these changes

2021-10-10 16:57 UTC, Kartikay304 commented
@gr455, Can I work on this issue?

2025-02-15 15:04 UTC, ThatDeparted2061 commented
@tachyons I think we can close this PR and raise another PR since some checks are failing and its stayed too long, I can open another PR for the same !

2025-05-19 16:34 UTC, closed without merging