Gif and video record feature
CircuitVerse/CircuitVerse pull request #2151
Opened 2021-03-13 14:58 UTC by ZadeAbhishek

Fixes #
Added GIF and Video recording feature 

#### Describe the changes you have made in this PR -
0.separate GIF and GIF-animated
1.Added stop button
2.User can also select frame rate .
3.Added video feature
4.Max limit to record GIF is 2 min i.e 120 sec

Limitation
Video recording has black background i have used WebRTC which is most commly used to record canvas and WebRTC does not support alpha channel yet. WebRTC will convert pixel blocks into I420 pixel format which has 24 bit channel and does not have support for Alpha channel. On the other end , stream will be converted back to another pixel but alpha channel information will be lost.

### Screenshots of the changes (If any) -
UI change 
![Screenshot from 2021-03-13 20-22-08](https://user-images.githubusercontent.com/66520848/111034077-fc8c7d80-8439-11eb-91fd-b211fe656bf2.png)

video  of example 
https://user-images.githubusercontent.com/66520848/111034151-42494600-843a-11eb-9dc3-a3bb4a608983.mp4

GIF example 
![Main (5)](https://user-images.githubusercontent.com/66520848/111034174-55f4ac80-843a-11eb-9a48-c4bdce8810ae.gif)

video
https://user-images.githubusercontent.com/66520848/111034197-74f33e80-843a-11eb-8c19-b35732290e05.mp4

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-03-15 08:11 UTC, ZadeAbhishek commented
@satu0king can you please review this PR.

2021-03-29 15:03 UTC, abstrekt requested changes
- Seems like a bug was introduced here with the project title 
![image](https://user-images.githubusercontent.com/42478217/112851835-f8629000-90c8-11eb-8924-bdb1be08a89a.png)
- Make sure proper color variables are set, check `color_theme.scss`, set proper color variables should fix this
![image](https://user-images.githubusercontent.com/42478217/112852569-aff7a200-90c9-11eb-8433-69ed86eab6ef.png)

- panning the canvas while recording breaks the gif (not in the case of video), as previous frames have old position gets captured along with the new position, 
one solution could be adding a backdrop with some opacity, set proper z-index & disable `pointer-event` to none? -- the idea here is to place this backdrop above everything but behind the stop recording button, acting as a barrier.

![image](https://user-images.githubusercontent.com/42478217/112853764-cf42ff00-90ca-11eb-90b0-a5ab49965098.png)
- I'm unable to verify if the framerate is actually set, still the default framerate should appear when opening the modal, and the limitation on the framerate range should be enforced in the modal itself.
- There are other style issues that you can come to later but the above suggestions are necessary for roll out.

2021-03-29 15:09 UTC, ZadeAbhishek commented
@abstrekt working on it .

2021-03-29 15:09 UTC, abstrekt commented
also, the commit counts are increasing in this PR-- makes it hard to do code review, make sure to squash (git rebase -i) similar & small commits like 
![image](https://user-images.githubusercontent.com/42478217/112857260-4ded6b80-90ce-11eb-874c-2f0f4df9da36.png)

& always use proper commit messages, not like this 
![image](https://user-images.githubusercontent.com/42478217/112857535-93aa3400-90ce-11eb-867e-087e67c2150d.png)

Tip: use code climate vscode extension to check the code climate issue in the editor itself.
👍🏻

2021-03-29 15:15 UTC, ZadeAbhishek commented
okay @abstrekt

2021-04-11 09:17 UTC, ZadeAbhishek commented
Hey @abstrekt I have done the changes please once review this one

2026-01-20 13:46 UTC, SAMREEN111-hash commented
Hi, I came across the old PR related to GIF/Video recording and found the idea very interesting.
I’m interested in working on this feature using the current codebase, but wanted to check if this is something maintainers would like to pursue now.
Any guidance on whether this is relevant and where to start would be really helpful. Thanks!

2026-05-26 14:49 UTC, closed without merging

2026-05-26 14:49 UTC, Me-Priyank commented
Outdated . no MediaRecorder/gif.js anywhere in current main