Hover
CircuitVerse/CircuitVerse pull request #2183
Opened 2021-03-19 18:07 UTC by ashutosh264

**Fixes** #2149 

Added hover effect to social icons

2021-03-19 19:16 UTC, ShreyaPrasad1209 requested changes
@ashutosh264 can you also add a screenshot which shows the changes you have made?

2021-03-20 06:59 UTC, Aayush-hub commented
@ashutosh264 Please add screenshots as said by @ShreyaPrasad1209 mam. Plus choose different (background respective) colours for hovering different icons, if you can do that.

2021-03-20 07:01 UTC, Aayush-hub reviewed
@ashutosh264 Please add screenshots as said by @ShreyaPrasad1209 mam. Plus choose different (background respective) colours for hovering different icons, if you can do that.

2021-03-25 08:09 UTC, ashutosh264 commented
Here is the screenshot of changes that I made, 
![Screenshot (1398)](https://user-images.githubusercontent.com/61512480/112439725-7a705300-8d6f-11eb-9343-b5cb41eb20fd.png)

2021-03-25 09:04 UTC, ShreyaPrasad1209 requested changes
@ashutosh264 I think the original color of the icons looks better. The hover effect is good though. @aayush-05 what do you think?

2021-03-27 03:22 UTC, ashutosh264 commented
Ok I will try using original colour icons.

2021-03-27 08:16 UTC, aayush-05 commented
I think a shadow would look good as a hover effect for these social icons; let us not change colors and keep it simple.

2021-03-27 11:55 UTC, abstrekt commented
Add a proper title.

2021-03-28 12:43 UTC, ashutosh264 commented
For colored icons, only scaling up on hover looks good![IMG_20210328_181100.jpg](https://user-images.githubusercontent.com/61512480/112752553-3e4c2500-8ff1-11eb-9a49-4434a52744b6.jpg)

2021-03-28 12:53 UTC, ShreyaPrasad1209 approved these changes
This looks good! 👍  Also, as suggested by @abstrekt , please update the title of this PR.

2021-03-28 13:44 UTC, Aayush-hub commented
@ashutosh264 Yes its a good idea. Please go ahead and commit the changes.

2021-03-28 13:44 UTC, Aayush-hub commented
> For colored icons, only scaling up on hover looks good![IMG_20210328_181100.jpg](https://user-images.githubusercontent.com/61512480/112752553-3e4c2500-8ff1-11eb-9a49-4434a52744b6.jpg)

@ashutosh264 Yes its a good idea. Please go ahead and commit the changes.

2021-03-28 20:02 UTC, ashutosh264 commented
I have committed changes & also updated title

2021-03-29 08:49 UTC, Aayush-hub approved these changes

2021-03-31 15:09 UTC, ashutosh264 commented
Anything else expected from my side?

2021-04-03 16:55 UTC, ShreyaPrasad1209 commented
I don't think so

2025-02-15 15:01 UTC, ThatDeparted2061 commented
@tachyons @SannidhiNair Close this PR , resolved in #2462

2025-02-15 15:16 UTC, closed without merging