Added the hover effect to Social icons
CircuitVerse/CircuitVerse pull request #2286
Opened 2021-06-16 10:59 UTC by deepaahuja92

Fixes #2149 

#### Describe the changes you have made in this PR -I have created the hover effect in the social icons by using the scale property in CSS.

![Screenshot (2279)](https://user-images.githubusercontent.com/76697041/122207717-0baf1b80-cec0-11eb-902b-2fc05e1789e1.png)

2021-06-16 11:25 UTC, deepaahuja92 commented
what is the issue in my pull request?

On Wed, Jun 16, 2021 at 4:51 PM codeclimate[bot] ***@***.***>
wrote:

> Code Climate has analyzed commit 2e7453c
> <https://github.com/CircuitVerse/CircuitVerse/commit/2e7453c8639dcc9d549ade1fedfbd4f9cd0bc889>
> and detected *1 issue* on this pull request.
>
> Here's the issue category breakdown:
> Category Count
> Style 1
>
> View more on Code Climate
> <https://codeclimate.com/github/CircuitVerse/CircuitVerse/pull/2286>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CircuitVerse/CircuitVerse/pull/2286#issuecomment-862296531>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASJE3UKOD6OLODW4MC4ZA43TTCCL3ANCNFSM46ZF5WWQ>
> .
>

2021-06-17 04:07 UTC, ShreyaPrasad1209 approved these changes

2021-08-18 17:13 UTC, nitin10s requested changes
The scale value looks odd, we can scale to max 1.1/1.2 (a subtle change)

2025-02-19 12:29 UTC, ThatDeparted2061 commented
issue has been resolved in [#2642](https://github.com/CircuitVerse/CircuitVerse/pull/2462)

2025-02-19 12:29 UTC, closed without merging