PR localization of views - logix
CircuitVerse/CircuitVerse pull request #2310
Opened 2021-06-30 12:46 UTC by pavanjoshi914

#### Describe the changes you have made in this PR -
localize logix module
extract repeated keys present in about page module and logix module in general namespace

### Screenshots of the changes (If any) -
![image](https://user-images.githubusercontent.com/55848322/123962161-c5cd7980-d9ce-11eb-994b-5d2994589ca7.png)

![image](https://user-images.githubusercontent.com/55848322/123962222-d7af1c80-d9ce-11eb-8302-9fb8a7b011a6.png)

![image](https://user-images.githubusercontent.com/55848322/123962291-ed244680-d9ce-11eb-9844-6e9b32af5068.png)

![image](https://user-images.githubusercontent.com/55848322/123962380-06c58e00-d9cf-11eb-9b48-5ca44ba14342.png)

![image](https://user-images.githubusercontent.com/55848322/123962591-3ffdfe00-d9cf-11eb-8401-4c7f8278134f.png)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-07-01 17:20 UTC, ShreyaPrasad1209 approved these changes

2021-07-03 06:01 UTC, Shivansh2407 requested changes
Great Work @pavanjoshi914 :tada: I have suggested a few minor changes, please update them and we'll be good to go.

2021-07-03 06:14 UTC, pavanjoshi914 commented on config/locales/views/logix/hi.yml
> +        main_description: "ड्रैग-एंड-ड्रॉप, कॉपी/पेस्ट, ज़ूम, और अधिक विशेषताओं का उपयोग करके आधुनिक और सहज यूजर इंटरफ़ेस के साथ डिजिटल सर्किट की रचना जल्दी और आसानी से करे।"
![image](https://user-images.githubusercontent.com/55848322/124345050-f17d7900-dbf3-11eb-8792-a0a2f1fdaaaa.png)

its rendering on my local system

2021-07-03 06:33 UTC, Shivansh2407 commented on config/locales/views/logix/hi.yml
> +        main_description: "ड्रैग-एंड-ड्रॉप, कॉपी/पेस्ट, ज़ूम, और अधिक विशेषताओं का उपयोग करके आधुनिक और सहज यूजर इंटरफ़ेस के साथ डिजिटल सर्किट की रचना जल्दी और आसानी से करे।"
It should be ड्रैग-एंड-ड्रॉप right? But it becomes different in the screenshot

2021-07-03 06:39 UTC, pavanjoshi914 commented on config/locales/views/logix/hi.yml
> +        main_description: "ड्रैग-एंड-ड्रॉप, कॉपी/पेस्ट, ज़ूम, और अधिक विशेषताओं का उपयोग करके आधुनिक और सहज यूजर इंटरफ़ेस के साथ डिजिटल सर्किट की रचना जल्दी और आसानी से करे।"
can you share me screenshot how it is rendered on your side

2021-07-03 06:40 UTC, pavanjoshi914 commented on config/locales/views/logix/hi.yml
> +      main_description: "साधारण गेट से लेकर काम्प्लेक्स सेकेंटिअल सर्किट्स, प्लॉट टाइमिंग डायग्राम, आटोमेटिक सर्किट जनरेशन, स्टैण्डर्ड आईसी के बारे में अधिक, और बहुत कुछ जानिए"
typo corrected

2021-07-03 06:40 UTC, pavanjoshi914 commented on config/locales/views/logix/hi.yml
> +      main_description: "सर्किटविर्स को कक्षा में उपयोग करने के लिए बहुत आसान बनाया गया है। मंच में शिक्षकों को कक्षा और असाइनमेंट में सहायता करने के लिए सुविधाएँ हैं।"
checked all the words starting from "circuit" typo is only at one place , corrected!!

2021-07-05 04:17 UTC, Shivansh2407 commented on config/locales/views/logix/hi.yml
> +        main_description: "ड्रैग-एंड-ड्रॉप, कॉपी/पेस्ट, ज़ूम, और अधिक विशेषताओं का उपयोग करके आधुनिक और सहज यूजर इंटरफ़ेस के साथ डिजिटल सर्किट की रचना जल्दी और आसानी से करे।"
> ![image](https://user-images.githubusercontent.com/55848322/124345050-f17d7900-dbf3-11eb-8792-a0a2f1fdaaaa.png)
> 
> its rendering on my local system

You can notice some difference in the above screenshot that you've shared, and in this word:ड्रैग-एंड-ड्रॉप

 ![SS](https://user-images.githubusercontent.com/42182955/124416943-ba36d580-dd75-11eb-9bf4-17590db85c61.png) -> ड्रैग-एंड-ड्रॉप

2021-07-05 06:15 UTC, tachyons commented
logix was the original name of circuitverse, not need to refer that anymore. also, 'general', Instead of `general.xyz`, you van just use `xyz`

2021-07-05 06:30 UTC, pavanjoshi914 commented
I am using rule  that translations will be put in ```folder_name + view_name````  namespace. as this will bring scalability and reduce key conflicts a lot in future.

here 
```
logix:
  contribute:
    ....
  ```
shall I change toplevel namespace from ```logix:``` to ```circuitverse:``` ?
this will break consistency as folder name is still logix

regarding ```general``` I used this word to define context  that is key is repeating key and used in other templates also.

if we just use ```email_us_heading```  contributors will not get idea that this key is also used in other templates also this key is placed in general folder.

Definitely it will reduce one level of nesting. To what I shall give priority here

2021-07-06 04:59 UTC, Shivansh2407 commented on config/locales/views/logix/hi.yml
> +        main_description: "ड्रैग-एंड-ड्रॉप, कॉपी/पेस्ट, ज़ूम, और अधिक विशेषताओं का उपयोग करके आधुनिक और सहज यूजर इंटरफ़ेस के साथ डिजिटल सर्किट की रचना जल्दी और आसानी से करे।"
As discussed on slack, this is some font rendering issue which can be skipped for now.

2021-07-06 05:00 UTC, Shivansh2407 approved these changes
Great Work @pavanjoshi914 :tada:

2021-07-06 05:19 UTC, pavanjoshi914 commented on config/locales/views/logix/hi.yml
> +        main_description: "ड्रैग-एंड-ड्रॉप, कॉपी/पेस्ट, ज़ूम, और अधिक विशेषताओं का उपयोग करके आधुनिक और सहज यूजर इंटरफ़ेस के साथ डिजिटल सर्किट की रचना जल्दी और आसानी से करे।"
already discussed with @tachyons

2021-07-06 11:55 UTC, tachyons commented
For the general use config/locales/locale.yml, like 'config/locales/hi.yml'

2021-07-06 14:23 UTC, pavanjoshi914 commented
changes made accordingly !!
CC @tachyons

2021-07-18 05:53 UTC, merged