Localize views errors
CircuitVerse/CircuitVerse pull request #2316
Opened 2021-07-06 09:45 UTC by pavanjoshi914

Fixes #

#### Describe the changes you have made in this PR -

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-07-06 11:34 UTC, tachyons commented on app/views/errors/not_found.html.erb
> +      <div class="error-code bold pt-5"><%= t("errors.not_found.error_code") %></div>
Error code is not to be translated, we can just keep using [Arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals)

2021-07-06 11:38 UTC, tachyons commented
I am skeptical about translating error pages, WDYT @satu0king ?

2021-07-06 16:10 UTC, ShreyaPrasad1209 requested changes

2021-07-06 16:10 UTC, ShreyaPrasad1209 commented on config/locales/views/errors/hi.yml
> +      error_description: "सर्वर त्रुटिपूर्ण!, यह मेरी वजह से है आप नहीं, आइए फिर से प्रयास करें :)"
This can be improved as - ye meri wajah se hai na ki aapki taraf se

2026-05-26 14:29 UTC, Me-Priyank commented
UI completely redesigned since

2026-05-26 14:29 UTC, closed without merging