Testbench/UI: New UI for Testbench on Simulator
CircuitVerse/CircuitVerse pull request #2330
Opened 2021-07-15 17:22 UTC by gr455

- Implemented new UI
 - Prototype Detailed Results UI
![New UI](https://user-images.githubusercontent.com/53974118/125830441-9eb0d65d-1f66-4dda-a54f-cab7ccfb94e3.gif)

2021-07-29 10:44 UTC, satu0king commented on simulator/src/data/backupCircuit.js
> +    data.test = scope.test;
```suggestion
    data.testBenchData = scope.testBenchData;
```
Rename variable to be more descriptive

2021-07-29 10:55 UTC, satu0king commented
![image](https://user-images.githubusercontent.com/2092958/127479961-fa3d1b8e-ec18-42b2-9532-c30b8c00d3b4.png)
Theme needs to be corrected here

2021-07-29 11:14 UTC, satu0king requested changes
Things to do:
1. Show error when validation fails (after testbench is created)
2. Allow testbench to be created even if validation fails
3. Fix the space issue in identifier name - use equivalent of `.strip()`
4. Edit Layout should not have testbench - Check where all timing diagram is toggled? Also replicate logic of timing diagram, or refactor both of them
5. When circuit is switched, testbench needs to be updated. 
6. Lots of small UI Improvements needed

2021-07-29 11:24 UTC, satu0king commented on simulator/src/testbench.js
> +            setUIResult(globalScope.test, currentGroup, currentCase, result);
The above 3 lines seem to be repeated everywhere, can this be improved? Like say we have a function which says
`testbench.setCurrentTestCase(testbench.currentGroup + 1, testbench.currentCase + 1);`
This function itself can validate if that specific action is possible etc and update the UI and run the test accordingly?

I think `currentGroup` and `currentCase` needs to be scoped as a class object to achieve the above.

2021-07-29 11:47 UTC, shubhankarsharma00 commented on simulator/src/utils.js
> +}
So this function is only used once to sanitize label input defined here earlier:
https://github.com/CircuitVerse/CircuitVerse/blob/2e1ae715d0e67d5e3068fa52fd0deaa8fcc35cb6/simulator/src/ux.js#L416
We don't use it anywhere else afaik.

2021-07-30 06:32 UTC, gr455 commented
Whoops messed up commit history. Closed in favor of https://github.com/CircuitVerse/CircuitVerse/pull/2366

2021-07-30 06:32 UTC, closed without merging