fix error message #2198
CircuitVerse/CircuitVerse pull request #2335
Opened 2021-07-15 20:03 UTC by Jayita10

Sign off: Jayita Pramanik

Fixes #2198 

#### Describe the changes you have made in this PR -

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-07-15 20:09 UTC, Jayita10 commented on simulator/src/node.js
> +                    showError(`ConstVal set to Non-binary value.`);
@ShreyaPrasad1209 please help me to pass the all test cases. Thank you

2021-07-15 20:16 UTC, ShreyaPrasad1209 requested changes
@Jayita10  can you attach screenshots of your changes? Also, there's no need to write "sign off: your name" in the PR description.

2021-07-15 21:11 UTC, Jayita10 commented
> @Jayita10 can you attach screenshots of your changes? Also, there's no need to write "sign off: your name" in the PR description.

Please review :)

2021-07-16 03:33 UTC, ShreyaPrasad1209 approved these changes
Great work @Jayita10 🎉

2021-07-16 03:33 UTC, merged

2021-07-16 04:28 UTC, tachyons commented
@satu0king

2021-09-09 16:43 UTC, gr455 commented
> This breaks contention message for other elements also :(

@Jayita10 I am reverting this commit because this breaks the error message for other elements too. Let me know if you would like to follow this issue up. Thanks!

2021-09-10 03:33 UTC, Jayita10 commented
> > This breaks contention message for other elements also :(
> 
> @Jayita10 I am reverting this commit because this breaks the error message for other elements too. Let me know if you would like to follow this issue up. Thanks!

@gr455 I'm working on this issue

2021-09-10 05:47 UTC, gr455 commented
> > > This breaks contention message for other elements also :(
> > 
> > @Jayita10 I am reverting this commit because this breaks the error message for other elements too. Let me know if you would like to follow this issue up. Thanks!
> 
> @gr455 Okay, I'm working on this issue

Amazing!
I think that it's better to add validation in ConstVal to not accept non-binary data instead of changing the error message because changing the error message for a single element is not easy