issue #2363 solved added redirection effect
CircuitVerse/CircuitVerse pull request #2373
Opened 2021-08-03 17:17 UTC by vedant-jain03

Fixes #2363 

#### Describe the changes you have made in this PR -
* added styles in lti.scss
* added the redirection feature in open_incv.html.erb 
* updated the UI of open_incv.html.erb

### Screenshots of the changes (If any) -

![Screenshot (91)](https://user-images.githubusercontent.com/76901313/128058196-32bf1378-384e-4058-ae96-ebc34728eb19.png)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-08-03 17:18 UTC, vedant-jain03 commented
@ayan-biswas0412 Kindly review!

2021-08-04 04:53 UTC, ayan-biswas0412 commented on app/assets/stylesheets/lti.scss
> +// Style-sheet for lti
I think we don't need any additional CSS for this and you can see the `app/views/lti/launch_error.html.erb` in which the container is already used but no additional css were required so delete the file and keep it as simple `container`

2021-08-04 04:54 UTC, ayan-biswas0412 commented on app/views/lti/open_incv.html.erb
> +<script>
Just use of a simple JS can be sufficient I think like 
```
<script>
    function redirectAfterLoad() {
        window.onload = function() {
            window.open(
                    "<%= group_path(@group) %>",
                    "_blank"
            );
        }
    }
    redirectAfterLoad();
</script>
```

2021-08-04 04:55 UTC, ayan-biswas0412 commented on app/views/lti/open_incv.html.erb
> +</script>
@vedant-jain03 also resolve this bot comments by changing as suggested

2021-08-04 04:59 UTC, ayan-biswas0412 requested changes
Please see the suggestions I have given in the code , and please note that there should not be any hardcoded English strings in the files , you can see `app/views/lti/launch_error.html.erb` where we have used `<%= t("launch_error.main-heading") %>` to load the string from the file `config/locales/controllers/lti/en.yml` , so it is better add your strings there and import that to the `app/views/lti/open_incv.html.erb`

2021-08-04 05:00 UTC, ayan-biswas0412 commented on app/views/lti/open_incv.html.erb
> +    <h4>Please wait while we open this assignment in CircuitVerse...</h4>
rather than using heading tags you can use `class="main-heading"` like the `app/views/lti/launch_error.html.erb`

2021-08-04 07:48 UTC, ayan-biswas0412 commented
also note it is required to pass all the CIs @vedant-jain03

2021-08-04 09:22 UTC, ayan-biswas0412 requested changes
Please resolve all them

2021-08-04 09:22 UTC, ayan-biswas0412 commented on config/locales/controllers/lti/en.yml
> +      notive_redirection_error: "If it doesn't work, please click the button below."
should be `notice` not `notive`

2021-08-04 09:22 UTC, ayan-biswas0412 commented on config/locales/controllers/lti/en.yml
> +      notive_redirection_error: "If it doesn't work, please click the button below."
you have too keep all these strings in `config/locales/views/lti/en.yml`

2021-08-04 11:15 UTC, vedant-jain03 reviewed
Resolved

2021-08-04 14:11 UTC, ayan-biswas0412 requested changes

2021-08-04 14:50 UTC, ayan-biswas0412 commented
@vedant-jain03 comment-lint PR is producing CI failures just change the title of the PR like something `fix: UI fixed or something`

2021-08-04 14:51 UTC, ayan-biswas0412 commented on config/locales/controllers/lti/en.yml
> +      notice_invalid_group: "There is no group in CircuitVerse associated with your current LMS, Please ask your LMS Admin/Teacher to create one"
delete this line also `notice_invalid_group` and keep the file unchanged like previous version

2021-08-04 15:15 UTC, ayan-biswas0412 commented on config/locales/controllers/lti/en.yml
> +
there is still an extra line

2021-08-04 15:15 UTC, ayan-biswas0412 commented on config/locales/controllers/lti/en.yml
> +
```suggestion
```

2021-08-04 15:58 UTC, ayan-biswas0412 approved these changes
Nice work 🎉

2021-08-04 16:00 UTC, vedant-jain03 commented
> Nice work 🎉

Thankyou for guiding :)

2021-08-05 14:40 UTC, Shivansh2407 approved these changes
Nice work @vedant-jain03 :tada: Looks good to me! 
Quick Tip :sparkles: : Make sure to squash the commits from next time onwards when you're done with the work on a PR.

Thanks & Happy Coding :+1:

2021-08-05 14:49 UTC, merged

2021-08-05 14:59 UTC, tachyons commented
URL in screenshot looks odd, it contain ruby code

2021-08-05 15:43 UTC, vedant-jain03 commented
> Nice work @vedant-jain03 🎉 Looks good to me!
> Quick Tip ✨ : Make sure to squash the commits from next time onwards when you're done with the work on a PR.
> 
> Thanks & Happy Coding 👍

Thanks Shivansh for merging, I will try to make clean PR from next time. :)

2021-08-05 15:51 UTC, vedant-jain03 commented
> URL in screenshot looks odd, it contain ruby code

Actually I have setup env. in gitpod for now and I think that is why it is looking odd, but you can see here : https://github.com/vedant-jain03/CircuitVerse/blob/b3fd1700a0198e905711e456a33a266f9888c987/app/views/lti/open_incv.html.erb that the page will redirect to group path.
I hope I cleared your doubt sir!