fixes: translation of open assignment string using i18n
CircuitVerse/CircuitVerse pull request #2517
Opened 2021-10-02 04:34 UTC by vedant-jain03

Fixes #2509 

#### Describe the changes you have made in this PR -

- added open_assignment key in en.yml
- added translation function in open_incv.html.erb

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-10-02 04:35 UTC, vedant-jain03 commented
@pavanjoshi914 @ayan-biswas0412 Kindly Review

2021-10-02 06:27 UTC, gr455 approved these changes
Looks Good

2021-10-02 06:37 UTC, pavanjoshi914 commented
Add translations in hi.yml as well if you know Hindi

2021-10-02 07:56 UTC, vedant-jain03 commented
> Add translations in hi.yml as well if you know Hindi

Thier is not hi.yml file for lti , can I make one and add this ?

2021-10-02 08:05 UTC, vedant-jain03 commented
> Add translations in hi.yml as well if you know Hindi

Sure

2021-10-02 08:07 UTC, vedant-jain03 commented
@pavanjoshi914 Kindly review

2021-10-02 11:28 UTC, gr455 approved these changes

2021-10-02 11:52 UTC, pavanjoshi914 requested changes

2021-10-02 15:17 UTC, vedant-jain03 commented on config/locales/views/lti/hi.yml
> +en:
@pavanjoshi914 Done

2021-10-02 16:02 UTC, pavanjoshi914 commented
Good work @vedant-jain03. please add screenshot of output to this PR

@tachyons  LGTM

2021-10-02 16:03 UTC, pavanjoshi914 approved these changes

2021-10-03 05:31 UTC, vedant-jain03 commented
![Screenshot (149)](https://user-images.githubusercontent.com/76901313/135741344-1d45110e-21b5-4ce5-88e7-41673cd7357b.png)

2021-10-04 06:43 UTC, Kartikay304 approved these changes

2021-10-04 07:22 UTC, tachyons approved these changes

2021-10-04 07:23 UTC, merged