Added a new button to create a new circuit in insert Subcircuit dialog
CircuitVerse/CircuitVerse pull request #2535
Opened 2021-10-09 09:18 UTC by Prerna-0202

Fixes #1751 

#### Describe the changes you have made in this PR -
Added a new button `New Circuit +` to create a new circuit in the `Insert Subcircuit` dialogue box.

### Screenshots of the changes (If any) -
<img width="924" alt="P2" src="https://user-images.githubusercontent.com/89515816/136652279-5c3236f7-6c52-4dee-a524-527962a31c17.png">
<img width="956" alt="pp" src="https://user-images.githubusercontent.com/89515816/136652283-cffcc8a5-f547-4332-b673-c66b0c0526fe.png">

2021-10-15 12:48 UTC, Prerna-0202 commented
@shubhankarsharma00 , Sir Thank you for suggesting the changes .I have made the changes in my pr  . Now please review it.

2021-11-01 16:07 UTC, shubhankarsharma00 commented
looks like you tried to merge master and the feature branch. you can make a new PR. or try to fix history for this one. Look into git reset -soft and if you are able fix the history then force push the changes. It's upto you if you want to make a new PR though just mention this there and close this one.

2021-11-01 16:49 UTC, gr455 commented
As Shubhankar said, you can try and fix this branch by doing `git reset --soft HEAD~n` where n is the number of commits you want reset. This will remove these commits and add the changes in these commits to staging. You can then git reset <filename>to unstage individual changes.

If this is too inconvenient, you can also close this PR and create a new one

2021-11-01 20:13 UTC, Prerna-0202 commented
@gr455 @shubhankarsharma00, I have made the changes . Can u please now review my pr and provide me with the feedback.

2021-11-02 06:18 UTC, gr455 requested changes
Looks good just one small issue. Let's say I create `circuit2` and put `Main` as a subcircuit in `circuit2`. then trying to insert subcircuits in `Main` should also show `No subcircuits` (since the only other circuit `circuit2` has `Main` as a dependency). But right now the UI bugs out and shows `Main` when inserting subcircuit in `Main`

2021-11-02 15:03 UTC, Prerna-0202 commented
Okay @gr455,  I will commit the changes as soon as possible.

2021-11-28 15:31 UTC, Prerna-0202 commented
@gr455 I have commit the changes and now it's working fine. Can you please review my pr ...

2021-12-01 15:20 UTC, gr455 approved these changes
Looks good to me

2021-12-22 14:22 UTC, Prerna-0202 commented
@gr455 @tachyons, Do I need to make more changes in this pr??

2021-12-22 14:38 UTC, tachyons commented on app/views/simulator/edit.html.erb
> +<div id="insertSubcircuitcontent"><span><p>Looks like there are no other circuits which doesn't have this circuit as a dependency. Create a new one!</p></span><a class="btn btn-xs custom-btn--primary
- Make the text translatable using i18n 
- move inline onclick if feasible

2021-12-22 21:05 UTC, Prerna-0202 commented
@tachyons, I have commit the changes by making the text translatable using i18n...and the second changes you said I think it's not feasible or if you have any idea please tell...

2022-01-12 04:58 UTC, Prerna-0202 commented
@tachyons, I have commit the changes by making the text translatable using i18n...and the second changes you said I think it's not feasible or if you have any idea please tell...

2023-02-03 10:14 UTC, Prerna-0202 commented
@tachyons I have moved the inline onclick and resolved bot issues. Please review.

2023-02-03 10:16 UTC, merged