Added a View Project Page Link in Project Dropdown Menu
CircuitVerse/CircuitVerse pull request #2566
Opened 2021-10-23 18:02 UTC by Prerna-0202

Fixes #808 

#### Describe the changes you have made in this PR -
I have added a View  Project Page Link in the Project Dropdown menu

### Screenshots of the changes (If any) -
<img width="958" alt="1" src="https://user-images.githubusercontent.com/89515816/138566860-a83d4735-e815-4286-905a-1a11d04bce5b.png">
onclick-
<img width="956" alt="2" src="https://user-images.githubusercontent.com/89515816/138566873-67ebb842-7a36-4996-b0ab-024d9057c47e.png">

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-11-05 18:06 UTC, Prerna-0202 commented
@tachyons @gr455 , do I further need to make any changes?

2021-11-25 19:33 UTC, Prerna-0202 commented
@tachyons @gr455 @nitin10s, do I further need to make any changes in this pr??

2021-11-30 03:31 UTC, nitin10s requested changes
Actually, the button should open the project page and not the user page as discussed in the issue

2021-11-30 19:29 UTC, Prerna-0202 commented
Okay @nitin10s, Thanks for reviewing. I will commit the changes as soon as possible...

2021-12-06 14:07 UTC, Prerna-0202 commented
@nitin10s, I think this issue has been done by someone previously but the pr didn't link to that issue. That's why I was not aware but now I have seen that this has been already done...
![Screenshot (58)](https://user-images.githubusercontent.com/89515816/144858889-269e0f48-746a-41fd-9267-80cba30e3001.png)




![Screenshot (59)](https://user-images.githubusercontent.com/89515816/144860000-77e84770-8efa-42fe-8f8f-67a5788cfb05.png)

2021-12-21 20:03 UTC, nitin10s commented
Which PR is that?

2021-12-23 03:33 UTC, Prerna-0202 commented
> Which PR is that?

@nitin10s , I don't know which pr is that but I saw Project Page link already in the drop-down and it is working fine  that's why I said. If I am wrong please correct me...

2026-05-26 15:38 UTC, closed without merging