Added a View option in menu bar Fixes: #1966
CircuitVerse/CircuitVerse pull request #2640
Opened 2021-11-21 18:23 UTC by pulkit-30

Fixes #1966 

#### Describe the changes you have made in this PR -

#### Requested Feature
View option in the menubar next to tools with 3 checklist options to view the Circuit elements, Timing Diagram help, and properties dialog box.

#### Changes 
Added view option in the menu bar with 3 checklists `Timing Diagram` `Circuit Properties` `Circuit Elements`.
which can toggle the display of respective properties.

### Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/76155456/142773706-ed10ddaa-fb44-4fc5-93fe-7ea1948e0065.mp4

Please provide me with appropriate feedback, so that I can continue working on this.

2021-11-22 15:50 UTC, pulkit-30 commented
Hey @gr455 , 
May you please help me out to resolve these errors. I tried to figure it out but was unable to come to a solution.

2021-11-25 14:09 UTC, gr455 commented
> Hey @gr455 , May you please help me out to resolve these errors. I tried to figure it out but was unable to come to a solution.

You can refer to [this link](https://www.456bereastreet.com/archive/201005/void_empty_elements_and_self-closing_start_tags_in_html/#:~:text=These%20elements%20are%20called%20empty,link%20%2C%20meta%20%2C%20and%20param%20.)

2021-11-25 17:07 UTC, pulkit-30 commented
Thanks @gr455  ,
I will commit changes soon.
May you please help me out with these CircleCl tests fail. Why did these tests fail?

2021-11-29 17:48 UTC, Kartikay304 commented
> Thanks @gr455 , I will commit changes soon. May you please help me out with these CircleCl tests fail. Why did these tests fail?

can you rebase your branch with CV master.

2021-11-30 03:35 UTC, pulkit-30 commented
> > Thanks @gr455 , I will commit changes soon. May you please help me out with these CircleCl tests fail. Why did these tests fail?
> 
> can you rebase your branch with CV master.

Yes , then?

2021-11-30 03:38 UTC, pulkit-30 commented
Sure I can!

2021-12-01 15:39 UTC, pulkit-30 commented
Hey @Kartikay304,
I have rebased the branch with CV master. 
Please review.

2021-12-09 13:36 UTC, pulkit-30 commented
Hey @gr455,
Please review this PR and provide me with appropriate feedback so that I can continue working on it.

2021-12-22 04:51 UTC, nitin10s commented
Why would someone want to hide circuit elements and properties panel? We have a preview option that does this if the user wants to view the full circuit. Though I like the idea for timing diagram

2021-12-22 07:11 UTC, pulkit-30 commented
> Why would someone want to hide circuit elements and properties panel? We have a preview option that does this if the user wants to view the full circuit. Though I like the idea for timing diagram

The [feature request]( #1966 ) is for the same, but you are right .
What should we do next?
What's the better way to implement the same only for the timing diagram?  @nitin10s

2022-02-05 17:24 UTC, pulkit-30 commented
I think this [idea](https://github.com/CircuitVerse/CircuitVerse/pull/2640#1966) can implement now, only for testbench and timing diagram dialogs
we can have a view option that hides and display timing diagram and testbench dialogs
WDTY @nitin10s @tachyons @gr455

2022-02-06 06:02 UTC, gr455 commented
> I think this [idea](https://github.com/CircuitVerse/CircuitVerse/issues/1966) can implement now, only for testbench and timing diagram dialogs
> we can have a view option that hides and display timing diagram and testbench dialogs
> WDTY @nitin10s @tachyons @gr455 

Yep sounds good

2022-04-24 06:46 UTC, gr455 requested changes
I think the older layouts for Testbench and Timing Diagram were better. Can we just hide them and keep their older design?

2022-04-24 09:06 UTC, pulkit-30 commented
> I think the older layouts for Testbench and Timing Diagram were better. Can we just hide them and keep their older design?

Yep! Using simple JS to hide and unhide them

2022-05-03 03:37 UTC, pulkit-30 commented
Hey @gr455, any suggestion on this

2022-05-04 16:22 UTC, gr455 commented
@pulkit-30 This works great. I think that be default, these should be visible (Otherwise people may not even know these features exist). What do you say?

2022-05-10 06:52 UTC, pulkit-30 commented
> @pulkit-30 This works great. I think that be default, these should be visible (Otherwise people may not even know these features exist). What do you say?

Default to be visible and options to hide these dialog boxes? This would be great 👍🏽

2026-04-24 13:06 UTC, closed without merging