Edit Project screen open in new tab
CircuitVerse/CircuitVerse pull request #2645
Opened 2021-11-25 16:58 UTC by pulkit-30

Fixes #1358 

#### Describe the changes you have made in this PR -

#### Before
Whenever a user clicks to save his project [online], he gets redirected to the Edit Project Screen losing his work area.

If he wants to work further on his project he needs to click on the update project button from the Edit Project Screen then click on Launch Simulator to get his circuit back.

#### After Changes

The Edit Project Screen opens in a new tab, on clicking on the `save online` button.

### Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/76155456/143478271-baac52f3-348f-4e59-8b52-a87ec74c10e5.mov

#### Code Reference:

```
target:'_blank'
```
To open the form in the new Tab.

-----

```
  setInterval(()=>{
            window.location.href =`/simulator/edit/${url_projectName}`;
        },1000);
```
`setInterval()` is used to redirect the page to `/simulator/edit/{project_name}` after clicking on the `save online` button . So that, the user can continue working on the project and save the changes in the current project.

Please provide me with appropriate feedback so that I can continue working on this

2021-11-30 03:13 UTC, nitin10s commented
@gr455 can you check this?

2021-12-05 12:36 UTC, gr455 commented on simulator/src/data/save.js
> +        const url_projectName = projectName.replace(/\s+/g, '-').toLowerCase();
This won't always be the project slug, say if two projects have the same name, then it will be suffixed by some random string.

2021-12-05 12:38 UTC, gr455 requested changes
I think the better way to achieve it is to save and not redirect to the edit screen and just have a flash message on the simulator which has a button to go to the edit screen. What do you say @nitin10s

2021-12-06 08:20 UTC, nitin10s commented
The idea is really nice but one problem with this approach is that we are hiding a lot of additional important information that users can configure while creating a new project like description, project access. The adoption for adding this information by explicitly clicking on a button in the flash message would be very low. 

Not sure what should be done... whatsay? Your views @tachyons ?

2021-12-09 13:50 UTC, pulkit-30 commented
What about a popup edit form?
When the user clicks on the save button, a popup edit form opens, User can update the details there and when he click on the update button he will be redirected to the `/simulator/edit/project_name` route. 
This way he can configure the important information like description, project access, etc. and he will not lose his work.

@gr455, @nitin10s,  @tachyons.

2021-12-13 04:06 UTC, tachyons commented
> The idea is really nice but one problem with this approach is that we are hiding a lot of additional important information that users can configure while creating a new project like description, project access. The adoption for adding this information by explicitly clicking on a button in the flash message would be very low.

That information is important for discoverability which is already not good in the platform. A popup with all the fields in the project creation page may work here

2021-12-22 04:53 UTC, nitin10s commented
Yeah popup could be a good way.

2021-12-22 07:12 UTC, pulkit-30 commented
Shall I go ahead? @nitin10s @tachyons @gr455

2026-04-24 13:06 UTC, closed without merging