Fix : Added Author name below the project name in favourite page  #1315
CircuitVerse/CircuitVerse pull request #2651
Opened 2021-11-26 13:33 UTC by pulkit-30

Fixes #1315 

#### Describe the changes you have made in this PR -

#### Before:
The circuits on the Favourites Page don't display the author name, which becomes confusing and that is important information that should be supplied.

#### Fixed Changes:
Added the author name below the project title to make it clear for the user which circuit belong to him and which one is forked.

### Screenshots of the changes (If any) -

<img width="1680" alt="Screenshot 2021-11-26 at 1 00 50 AM" src="https://user-images.githubusercontent.com/76155456/143587935-7925a69b-4dc1-4156-82fc-3a403e802c31.png">

Please provide me with appropriate feedback so that I can continue working on this.

2021-11-28 19:07 UTC, Kartikay304 requested changes
Great work LGTM, Make climate happy and I think reducing the padding between project_name,author_name, and tag will make it more appealing.

2021-11-29 13:28 UTC, pulkit-30 commented
Hey @Kartikay304 
Thanks for your review, Surely I will commit these recommended changes asap!

2021-11-29 14:21 UTC, pulkit-30 commented
Hey @Kartikay304,
I have committed the recommended changes, please have a look.

Screenshot of the Chnages:
<img width="1418" alt="Screenshot 2021-11-29 at 7 38 06 PM" src="https://user-images.githubusercontent.com/76155456/143883799-b6a4c7c5-9536-4024-91d4-1f41120681d5.png">

2021-11-29 17:35 UTC, vedant-jain03 approved these changes

2021-11-29 17:43 UTC, Kartikay304 approved these changes
Great!, it looks good.Whatsay @nitin10s.

2021-11-30 03:18 UTC, nitin10s requested changes
The design needs a lot of work, can you come up with some designs? Post them on #ux channel and once finalised, you can make the changes.

2021-11-30 03:41 UTC, pulkit-30 commented
Sure @nitin10s,
I will propose some new designs.

2022-01-06 06:00 UTC, pulkit-30 commented
Hey @nitin10s , 
I come up with a design
![Card (2)](https://user-images.githubusercontent.com/76155456/148336068-d7727f00-10f5-4152-8aad-8057072322dc.png)
Please review this!

2026-04-24 13:06 UTC, closed without merging