Header Search Bar
CircuitVerse/CircuitVerse pull request #2664
Opened 2021-12-02 17:11 UTC by Sarfraz-droid

Feature #2662 

Changed navbar

### Screenshots of the changes (If any) -

![Screenshot from 2021-12-02 22-40-43](https://user-images.githubusercontent.com/73013838/144469954-37297258-b369-485c-b754-ed78f166e79a.png)

2021-12-02 18:54 UTC, Kartikay304 requested changes
Nice work but, the design is not looking good. It needs some changes. Can you make some new designs and post them on the #ux channel for mentors to finalize. Once the design gets approved, then you can make the required changes.Whatsay @gr455

2021-12-02 19:16 UTC, Sarfraz-droid commented
Ohkk! @Kartikay304

2021-12-06 07:56 UTC, Sarfraz-droid commented
@Kartikay304 I haved changed UI of the search bar. You may have a look at itt

2021-12-08 06:37 UTC, Kartikay304 commented
> @Kartikay304 I haved changed UI of the search bar. You may have a look at itt

Hello,
Can you send the screenshot of the preview, after you have made changes?

2021-12-11 17:36 UTC, Sarfraz-droid commented
@Kartikay304 

![image](https://user-images.githubusercontent.com/73013838/145686139-b9a774ab-2f08-4f8a-87ea-4ae426deddc1.png)

2025-05-27 08:50 UTC, closed without merging