adding border to the text box
CircuitVerse/CircuitVerse pull request #2711
Opened 2021-12-14 14:19 UTC by Shilpashreemr

#2699

2021-12-17 12:36 UTC, Kartikay304 requested changes
Great work! But the design does not appear to be very appealing. Can you make some designs and post them in the #ux channel on slack.

2021-12-19 16:46 UTC, Shilpashreemr commented
okie.

2021-12-22 04:54 UTC, nitin10s commented
This needs to change everywhere and not just on this popup, yeah lets come with some proper design and meanwhile keep this PR on hold

2026-05-30 09:00 UTC, aryanndwi123 commented
Closing this PR since it is a stale PR and has merge conflicts !!! 🔍

2026-05-30 09:00 UTC, closed without merging