Added Color Property in Hexdisplay, SevenSegDisplay, VariableLed, SixteenSegDisplay
CircuitVerse/CircuitVerse pull request #2741
Opened 2021-12-25 17:48 UTC by pulkit-30

Fixes #49 

#### Describe the changes you have made in this PR -
Added Color Property in Hexdisplay, SevenSegDisplay, VariableLed, SixteenSegDisplay.

### Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/76155456/147390616-11d6a0c8-f687-4c6d-b17e-11f293fc9534.mov

Kindly provide me with appropriate feedback so that I can continue working on this.

2021-12-26 03:24 UTC, vedant-jain03 commented
@pulkit-30 @nitin10s Can we add a color palette input as well that will provide easiness to the user to select a color.

2021-12-26 13:19 UTC, pulkit-30 commented
> @pulkit-30 @nitin10s Can we add a color palette input as well that will provide easiness to the user to select a color.

Sure @vedant-jain03, great Idea 💡
But I think, we need to first think and work on the code optimization, once the code is optimized and clean we can work on this as well ;)

2021-12-28 12:50 UTC, pulkit-30 commented
Hey @tachyons @gr455, Please review this PR.. and Kindly provide me with appropriate feedback so that I can continue working on this.

2021-12-29 06:35 UTC, gr455 commented
> Hey @tachyons @gr455, Please review this PR.. and Kindly provide me with appropriate feedback so that I can continue working on this.

I will review this in a couple of days. Sorry for the delay

2022-01-08 06:45 UTC, pulkit-30 commented
Hey @gr455, Please review

2022-01-09 06:18 UTC, gr455 commented on simulator/src/modules/SevenSegDisplay.js
> +        var dotColor = ["lightgrey", this,actualColor][this.dot.value] || "lightgrey"
Whoops, typo here. `this.actualColor`

2022-01-09 06:24 UTC, gr455 requested changes
VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit)

2022-01-09 07:04 UTC, pulkit-30 commented
> This works great mostly! Thanks a lot! Extremely sorry for the late review
> 
> VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit).
> 
> Also fix codeclimate, rest all looks good 👍

Great, thanks @gr455,
I will look into this and commit the changes as soon as possible .

2022-01-09 07:05 UTC, gr455 commented
> > This works great mostly! Thanks a lot! Extremely sorry for the late review
> > VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit).
> > Also fix codeclimate, rest all looks good +1
> 
> Great, thanks @gr455, I will look into this and commit the changes as soon as possible .

Yep take your time

2022-01-09 09:54 UTC, pulkit-30 commented
>VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit).

Hey @gr455,
May you please help me out reproducing this.

2022-01-09 15:34 UTC, gr455 commented
> > VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit).
> 
> Hey @gr455, May you please help me out reproducing this.

Add a variable LED to the main circuit, go to `Edit Layout`, put drag and drop the LED onto the subcircuit

Then create a new circuit. Add Main's subcircuit to this circuit and attatch an input to the LED and see the color

2022-01-10 20:26 UTC, pulkit-30 commented
> VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit).

Fixed!
May help me with this error 

<img width="798" alt="Screenshot 2022-01-11 at 1 52 45 AM" src="https://user-images.githubusercontent.com/76155456/148833808-d960d5c8-fd49-41e0-aa1d-63c751cbd8b9.png">

2022-01-15 05:57 UTC, gr455 commented
> > VariableLED is not changing color in a subcircuit (it does change on the actual element on the parent circuit).
> 
> @gr455 , this issue is Fixed! May you help me with this error
> 
> <img alt="Screenshot 2022-01-11 at 1 52 45 AM" width="798" src="https://user-images.githubusercontent.com/76155456/148833808-d960d5c8-fd49-41e0-aa1d-63c751cbd8b9.png">
> 
> Thanks in advance hugs

I think that's okay

2022-01-15 06:56 UTC, pulkit-30 commented
> I think that's okay

Great! Thanks

2022-01-15 16:15 UTC, gr455 approved these changes
Looks good to me. Thanks!

2022-01-17 05:23 UTC, Prerna-0202 approved these changes

2022-01-20 06:02 UTC, pulkit-30 commented
Hey @tachyons , Please check this PR.

2022-01-20 07:53 UTC, merged