Made input bar corners as same as input fields in project properties box on simulator page.
CircuitVerse/CircuitVerse pull request #2751
Opened 2021-12-31 16:49 UTC by Creatoon

Fixes #2710 

#### Describe the changes you have made in this PR -
Just corrected the border-radius property of .input-search class selector correct

### Screenshots of the changes (If any) -
![newSimulator](https://user-images.githubusercontent.com/65965202/147832952-c2e33e2b-b8ec-43d0-88df-609febde59b4.png)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2021-12-31 18:22 UTC, Kartikay304 approved these changes

2022-01-01 02:58 UTC, vedant-jain03 requested changes
@Creatoon Make search input center its left margin is less than right one.

2022-01-01 12:58 UTC, Creatoon commented
@vedant-jain03 I have centered the input box as you can see down.

![circuit2](https://user-images.githubusercontent.com/65965202/147850982-8c14dc9e-29a0-4e91-bd58-ee16ed8ae70e.png)

also, Can I make the placeholder color white as same as the other input box placeholders, after implementation,  it will look like.

![circuit3](https://user-images.githubusercontent.com/65965202/147851027-a5933a96-1eca-4f18-a2fa-cd299d3adaac.png)

2022-01-01 15:21 UTC, vedant-jain03 commented
> 

I think the current color for the placeholder looks good. Let's wait for @nitin10s review.

2022-01-01 15:22 UTC, vedant-jain03 approved these changes

2022-01-17 05:27 UTC, Prerna-0202 approved these changes

2026-05-30 11:37 UTC, aryanndwi123 commented
Closing this PR as it is a stale PR!! and has merge conflicts 🧱

2026-05-30 11:37 UTC, closed without merging