Improve embed feature
CircuitVerse/CircuitVerse pull request #2768
Opened 2022-01-08 20:50 UTC by Kartikay304

Ref #1938

#### Describe the changes you have made in this PR -
improved embed feature, added border-width&color and iframe-width&height

- [x] Iframe width and height.
- [x] Border width and colour.
- [ ] Change theme,Landing Circuit Tab
- [ ] Optionally Disable stuff like Clock Enable/Clock Time Interval/Zoom

### Screenshots of the changes (If any) -

### BEFORE

https://user-images.githubusercontent.com/40604582/148659489-bd5998ed-5a06-4b73-9e45-8bcf14ee9137.mp4

### AFTER

https://user-images.githubusercontent.com/40604582/148659407-a99110a7-d105-4a33-af00-4c036891978e.mp4

2022-01-08 20:54 UTC, Kartikay304 commented
@tachyons @nitin10s @gr455  Kindly review my PR.

2022-01-09 05:05 UTC, vedant-jain03 commented
@Kartikay304 Can we increase the margin of textarea.

2022-01-09 05:19 UTC, Kartikay304 commented
> @Kartikay304 Can we increase the margin of textarea.

Sure we can increase the margin around the text area but, I intentionally designed the text area this way, lets wait for Nitin's review for improvements in design.

2022-01-09 06:39 UTC, gr455 commented
Can we put default values on the embed modal (say width 500, height 500). So that someone can just quickly generate an embed

2022-01-09 07:06 UTC, gr455 commented
> @tachyons @nitin10s @gr455 Sir, can you please take a look at my PR.

Also you don't need to call anybody 'sir' haha :sweat_smile:

2022-06-18 12:48 UTC, tachyons commented on app/views/projects/show.html.erb
> +                  aria-labelledby="mySmallModalLabel"
Update the label here

2022-06-18 12:49 UTC, tachyons commented on app/views/projects/show.html.erb
> +  function edit_embed(){
Can we use stimulus-js here to cleanup the implementation ?

2022-06-27 05:09 UTC, vedant-jain03 commented
@Kartikay304 Thank you for your valuable contribution. This PR needs to be completed ASAP and is now considered under GSoC22 Platform Improvement Project. I am going to work on it from now!

Thankyou 🎉

2022-06-28 09:15 UTC, vedant-jain03 commented
@tachyons @nitin10s @pavanjoshi914 @abstrekt Kindly review.

2022-07-01 03:50 UTC, vedant-jain03 commented on app/javascript/controllers/projects_controller.js
> +        $('#advance-embed').change((e) => {
Expected

2022-07-01 08:36 UTC, tachyons commented on app/component/project_embed_component.html.erb
> +                <h6>Zoom In/Out</h6>
These texts need to translatable

2022-07-01 09:51 UTC, gr455 requested changes
Disabling zoom seems to not work (tested on chrome lastest)

2022-07-01 12:15 UTC, vedant-jain03 commented
> Disabling zoom seems to not work (tested on chrome lastest)

https://user-images.githubusercontent.com/76901313/176892332-9f03f6b8-c2a8-41cc-aaae-ef8172752441.mp4

@gr455 have a look at this clip, is that the same as what you did for disabling the zoom-in-out?

2022-07-05 05:54 UTC, vedant-jain03 commented on app/component/project_embed_component.html.erb
> +            <textarea name='embed-textarea' class="form-control form-input embed-link-textarea" rows="5px" column="115px" id="result" readonly></textarea>
It is readonly textarea, Not Needed!

2022-07-05 06:04 UTC, vedant-jain03 commented on app/component/project_embed_component.html.erb
> +            <textarea name='embed-textarea' class="form-control form-input embed-link-textarea" rows="5px" column="115px" id="result" readonly></textarea>
It is readonly textarea, Not Needed!

2022-07-05 06:28 UTC, tachyons commented on app/javascript/controllers/projects_controller.js
> +        flag = !flag;
if you are using this for toggler, you can simplify by using https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

2022-07-05 12:09 UTC, merged

2022-07-05 12:10 UTC, tachyons commented
Great job @vedant-jain03 and @Kartikay304 🎈