solved signout functionality
CircuitVerse/CircuitVerse pull request #2769
Opened 2022-01-09 13:54 UTC by khareyash05

Fixes #2746 

Fixed signout functionality

2022-01-10 14:31 UTC, tachyons requested changes
This PR just redirects the user to home page. Use link_to helper instead: Ref: https://stackoverflow.com/questions/25659488/using-link-to-with-delete-action-in-rails

2022-01-12 01:52 UTC, khareyash05 commented
@tachyons So i just have to add this line `link_to 'Delete', manage_user_path(user), method: :delete` instead of `/` . RIght??

2022-01-16 12:00 UTC, tachyons commented on app/views/layouts/_header.html.erb
> +            <a class="dropdown-item" rel="nofollow" data-method="delete" href="<%= link_to "Logout", destroy_user_session_path, :method => :delete %>"><%= t("sign_out") %></a>
Here you are trying to embed an acnhor tag inside anchor tag, try following this guide to get basic understanding about the rails syntax https://guides.rubyonrails.org/getting_started.html

2022-07-25 18:50 UTC, pulkit-30 commented
Hey @khareyash05 , 
Are you working on this issue?

2023-02-06 13:26 UTC, tachyons commented
Closing due to inactivity

2023-02-06 13:26 UTC, closed without merging