Apply padding to tools submenu button#2652
CircuitVerse/CircuitVerse pull request #2807
Opened 2022-01-19 09:08 UTC by rohit-raje-786

Fixes #2652 

#### Describe the changes you have made in this PR -Applied padding to the tools submenu button in the simulator.

### Screenshots of the changes (If any) -
Before:
![143591781-17c15797-a34d-4278-a5c8-166877544cfe](https://user-images.githubusercontent.com/61861303/150098557-f7ebdb0c-f872-413e-a6e9-e3f4029b72fd.jpeg)

After:

<img width="751" alt="Screenshot 2022-01-19 at 12 42 57 PM" src="https://user-images.githubusercontent.com/61861303/150098653-5837d4f5-42c6-4439-9050-3255d933fa0c.png">
<img width="549" alt="Screenshot 2022-01-19 at 12 43 19 PM" src="https://user-images.githubusercontent.com/61861303/150098673-b29a7a3e-13f1-495d-828f-e7256a97aca0.png">

Video Demonstration:https://www.loom.com/share/00cbb0bb3f5a4a42bb1f77ddad2b03f4

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2022-01-19 10:17 UTC, ayan-biswas0412 requested changes
please resolve hound bot comments and codeclimate issues

2022-01-19 11:36 UTC, rohit-raje-786 commented
@ayan-biswas0412 is there any extension like preetier such that after saving it get formatted ,so that no hound and code climate issues will apper,because i am using gitpod and I have to manually resolve this issues

2022-01-19 12:13 UTC, rohit-raje-786 commented
@ayan-biswas0412 code-climate is saying that not to use !important ,if don't use it the issuse regarding the bug won't get solved,what to do here?

2022-01-19 12:39 UTC, ayan-biswas0412 commented
> @ayan-biswas0412 code-climate is saying that not to use !important ,if don't use it the issuse regarding the bug won't get solved,what to do here?

cc @nitin10s can you please help regarding this

2022-01-23 11:59 UTC, tachyons commented
> @ayan-biswas0412 code-climate is saying that not to use !important ,if don't use it the issuse regarding the bug won't get solved,what to do here?

https://uxengineer.com/css-specificity-avoid-important-css/

2022-01-23 12:10 UTC, tachyons commented on app/views/simulator/edit.html.erb
> +$('.dropdown-caret').click(function(){
You don't need javascript to do this,  you can just use plain css by checking if parent dom object is having 'show' class

2026-05-28 18:53 UTC, closed without merging

2026-05-28 18:53 UTC, naman79820 commented
stale pr