feature: verilog-themes #2829
CircuitVerse/CircuitVerse pull request #2859
Opened 2022-01-29 08:32 UTC by devartstar

Fixes # 2829

#### Changes you have made in this PR -
Added a drop-down menu with 50+ themes to select from for editor in verilog panel window.
On clicking apply theme it would apply changes in the theme without refreshing the page/ erasing the contents in editor.

### Screenshots of the changes (If any) -
https://user-images.githubusercontent.com/61665451/151653937-8fbdd5ae-a9b4-4073-98c8-5fd2e1665255.mov

2022-01-29 11:47 UTC, ayan-biswas0412 requested changes
Can you remove the `apply changes` button and just when user selects the theme it will change in background ?

2022-01-29 11:53 UTC, devartstar commented
> Can you remove the `apply changes` button and just when user selects the theme it will change in background ?
Sure I will make that change.

2022-01-30 05:16 UTC, devartstar commented
@ayan-biswas0412 
I have made the change.
Can you please check it.

https://user-images.githubusercontent.com/61665451/151687622-ba1dbfdb-c05b-4cc6-a3f3-64fc6d5512a8.mov

2022-01-30 06:34 UTC, ayan-biswas0412 commented
> @ayan-biswas0412 I have made the change. Can you please check it.
> 
>  updatedVerilogTheme.mov

yah nice 🎉

2022-02-28 17:49 UTC, gr455 commented
The feature looks great. But do you think we need to give these many options for themes? Mostly people would just want a couple light and couple dark themes. The options seem a little too many don't you think @devartstar?

If you also feel that way, can we choose a few of them and display them?

2022-03-01 05:43 UTC, devartstar commented
@gr455 Though there is no harm in giving these many options but there is also no need. 
I agree that just having some selected 5 to 6 light and dark themes would be better for user experience.
I will select some most used themes and make the changes.

2022-03-02 05:28 UTC, merged

2022-03-03 13:00 UTC, devartstar commented
> Amazing thank you so much! You can also try to have the theme persist in circuit data in another PR. Merging this one for now

Sure, I would like to work on it.
Can you please clarify what you meant by `theme persist in circuit data`.

2022-03-06 04:40 UTC, gr455 commented
> > Amazing thank you so much! You can also try to have the theme persist in circuit data in another PR. Merging this one for now
> 
> Sure, I would like to work on it. Can you please clarify what you meant by `theme persist in circuit data`.

Oh as in, currently if I set some theme, then I save and refresh. Then load the circuit, the theme for verilog editor goes back to default. Can we have it so that it persists?

2022-03-06 17:47 UTC, devartstar commented
> > > Amazing thank you so much! You can also try to have the theme persist in circuit data in another PR. Merging this one for now
> > 
> > 
> > Sure, I would like to work on it. Can you please clarify what you meant by `theme persist in circuit data`.
> 
> Oh as in, currently if I set some theme, then I save and refresh. Then load the circuit, the theme for verilog editor goes back to default. Can we have it so that it persists?

I have created an issue for it and made a [PR#3006](https://github.com/CircuitVerse/CircuitVerse/pull/3006) which solves this.
Kindly review it whenever you are free.