Project recovery and autosave feature#2957
CircuitVerse/CircuitVerse pull request #2980
Opened 2022-03-01 17:01 UTC by devartstar

Fixes #2957  #34 

#### Describe the changes you have made in this PR -

**General Logic for Auto-save or Recovery :-**
- The Auto-save or Recovery only starts after some changes are made to current project because the user might be just viewing the project.
- The are 4 variables to alter - 
          - `changeCounter` - counts the number of changes, increments by 1 with all necessary mouse events, cut, copy, delete, paste, undo, redo..etc. 
          - `changeCounterLimit` : number of changes after previous save on which to call auto-save/recover
          - `smallInterval` : the number of seconds after which we check if `changeCounter` > `changeCounterLimit` then call auto-save/recover.
          - `bigInterval` : the number of seconds after which we will do autosave/recover
          
**Why use 2 Intervals ?**
- Autosaving after each necessary change event wont be feasible. so after every x sec (`smallInterval`) we check if some number (`changeCounterLimit`) of changes has been done then autosave.
- Autosaving only after some y sec (`bigInterval`) is not feasible as the user might have done a lot of changes in that bigInterval and just before the bigInterval completes somethng happens and looses his data.

**So why not only change counter with small interval ?** 

Because on using both `change Counter with small Interval` and `Big Interval` together it gives us the flexibility of having a relatively big value of `changeCounterLimit`. Eg. If we have some limit of 20 then if user stops after 10 to 15 changes the big interval will make sure that after some time those 10 to 15 changes are saved.
For autosave/recovery we have to call the `generateSaveData()` function and it takes some time. 
So main reason to use them together is to make call for auto-save/recovery effectively.

**Why not use update() function as reference for auto-save ?**

Scheduled Update function is called every 0.5 seconds which calls update along with other calls so it will call auto-save (`generateSaveData()` function) every 0.5 sec so it is not feasible.
<img width="679" alt="update" src="https://user-images.githubusercontent.com/61665451/156211495-a799ce32-fc66-48a6-b40c-770010e97bb8.png">

------------------------
#### Task1 : Project Recovery -
When the project is neither saved online or offline. 
Just keeping data of the latest unsaved project in local storage using the logic described above.

https://user-images.githubusercontent.com/61665451/156211554-2b97970e-fba9-4b9d-8f7a-9da2f837bdb9.mov

------------------------
 #### Task2 : Auto-save
Keep updating the data of the previously saved circuit according to the logic described above.
If project is saved online, creating a copy of it offline and keep updating the data in save offline.

https://user-images.githubusercontent.com/61665451/156212073-7669748c-ae34-46c1-8854-ef7892c850c7.mov

Also Save successful message in bottom is displayed only when we manually save, not on every auto-save call

------------------------
 #### Task3 : Checking for latest edits on opening project from server
On opening a project from server, check if same project is present in Local Storage.
If found, the compare the time of the last saved changes. (also added a field in data object to store time of the last saved changes).
If time for last saved changes 
(online) == (offline)
   Show message - `${projectName} is up to date`
(online) < (offline)
   Show message  - `{projectName} has some recent unsaved edits which are saved offline`

https://user-images.githubusercontent.com/61665451/156213473-88213af6-7856-4179-bb39-e7db02ca20c0.mov

@tachyons @gr455 @ayan-biswas0412 @abstrekt can you please review it and suggest the changes required.

2022-03-05 23:22 UTC, devartstar commented on simulator/src/ux.js
> +        if (localStorage.getItem(projectId) != null || __logix_project_id != 0) {
It has to be != we don't want strict inequality !== as we don't want to compare between string and null (null object)

2022-03-05 23:58 UTC, devartstar commented
https://user-images.githubusercontent.com/61665451/156903565-9a888fd2-877e-46c2-b25a-b8d88bef323d.mov

Added a dialog box for Recover Project.

2022-03-14 13:26 UTC, gr455 requested changes
Seems like there are some conflicts now. My bad for reviewing this late, can you please resolve the conflicts?

2026-05-27 14:27 UTC, Me-Priyank commented
Outdated. Simulator now lives in cv-frontend-vue repo

2026-05-27 14:27 UTC, closed without merging