For feature request with respect to issue #3378
CircuitVerse/CircuitVerse pull request #3408
Opened 2022-12-17 12:25 UTC by cAmartya

Fixes #

#### Describe the changes you have made in this PR - Added GitHub-action workflow for welcoming first-time-contributor on raising the PR.

### Screenshots of the changes (If any) -
Added .github/workflows/welcome.yml

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2022-12-17 12:47 UTC, cAmartya commented
hey, @vedant-jain03 can you please review the commit.

2022-12-20 17:43 UTC, vedant-jain03 requested changes
@gr455

2022-12-20 17:43 UTC, vedant-jain03 commented on .github/workflows/welcome.yml
> +             Thanks for opening your first issue here!
```suggestion
             Thanks for opening your first issue here. We are glad to see your interest in enhancing CircuitVerse. We recommend getting this reviewed by the community once in the slack #community channel. 
```

2022-12-20 17:43 UTC, vedant-jain03 commented on .github/workflows/welcome.yml
> +            Congrats on merging your first pull request! You can checkout the contribution guidelines [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/CONTRIBUTING.md).
```suggestion
            Congratulations on getting your first pull request merged. Welcome to the CircuitVerse community. We hope you continue contributing to CircuitVerse and improving CircuitVerse. You can check out the contribution guidelines [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/CONTRIBUTING.md).
```

2026-05-25 16:18 UTC, ShinichiShi commented
closing this as per this comment : https://github.com/CircuitVerse/CircuitVerse/issues/3378#issuecomment-2659216767

2026-05-25 16:18 UTC, closed without merging