revamp: search input in dashboard
CircuitVerse/CircuitVerse pull request #3412
Opened 2022-12-17 18:45 UTC by devarsh-mavani-19

Fixes #3379

#### Describe the changes you have made in this PR -
I have added border in scss file and added classes to search input field in index.html.erb file

### Screenshots of the changes (If any) -
![Screenshot from 2022-12-18 00-07-31](https://user-images.githubusercontent.com/55136047/208256883-ff159ab2-267a-46ff-8ca4-396619fb795f.png)
![Screenshot from 2022-12-17 23-19-50](https://user-images.githubusercontent.com/55136047/208256887-899fe059-f7a5-438d-922c-196dfc6b73b6.png)

2022-12-17 18:46 UTC, devarsh-mavani-19 commented
@vedant-jain03 Can you please check this PR?

2022-12-20 17:35 UTC, vedant-jain03 requested changes
![Screenshot from 2022-12-20 23-05-07](https://user-images.githubusercontent.com/76901313/208730216-b10e4963-7aa1-4b82-8f60-1db0a833e5a1.png)


@devarsh-mavani-19 WDYT of this?

2022-12-31 18:27 UTC, anasaijaz commented on app/views/users/circuitverse/index.html.erb
> +      <span><i class="fas fa-search search-icon-dashboard"></i><input type="search" class="users-circuits-search form-control form-input navbar-search-bar-input" placeholder="<%= t("users.circuitvers
@vedant-jain03 Can you please help me here I am confused? This branch is not merged still the issue is fixed in main branch?

2023-01-01 10:11 UTC, vedant-jain03 commented on app/views/users/circuitverse/index.html.erb
> +      <span><i class="fas fa-search search-icon-dashboard"></i><input type="search" class="users-circuits-search form-control form-input navbar-search-bar-input" placeholder="<%= t("users.circuitvers
@anasaijaz You can update your branch and work on requested changes

2023-05-23 06:25 UTC, closed without merging