fixes: Pagination is not in the center of the page #3469
CircuitVerse/CircuitVerse pull request #3476
Opened 2023-01-08 17:51 UTC by MauryanKansara

Fixes #

fixed the pagination and made it placed in the center as described in #3469 
I have also used "flex-wrap: wrap" so the pagination should be responsive for the smaller screens.

### Screenshots of the changes (If any) -
![users-op](https://user-images.githubusercontent.com/86093112/211211097-e7244d4f-e8ae-4585-a204-618e84108d1a.png)
![projects-op](https://user-images.githubusercontent.com/86093112/211211100-a034dd09-7dea-4972-ba31-9d148c9cb693.png)

2023-01-09 13:21 UTC, vedant-jain03 approved these changes
@MauryanKansara Thank you for your PR, great Job!
Welcome to CircuitVerse community 🎉

2023-02-03 05:39 UTC, tachyons requested changes
Codeclimate warnings are closed without addressing them.

2023-03-30 05:09 UTC, MauryanKansara commented
> @MauryanKansara Thank you for your PR, great Job! Welcome to CircuitVerse community 🎉

Hey @vedant-jain03 can you please merge this PR? You've already approved these changes....

2026-05-25 16:16 UTC, ShinichiShi commented
closing this as issue is resolved

2026-05-25 16:16 UTC, closed without merging