fix: update ui for comment input
CircuitVerse/CircuitVerse pull request #3521
Opened 2023-01-24 14:22 UTC by Sauvic016

Fixes #3494 

#### Describe the changes you have made in this PR -
- Comment input box size is changed to enhance user experience for multi-line input.

### Screenshots of the changes (If any) -
![image](https://user-images.githubusercontent.com/72251657/214318899-cd1e9ec3-dde6-40ef-960d-9306d854498b.png)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-01-25 10:53 UTC, vedant-jain03 requested changes
@Sauvic016 Thanks for the contribution.

If you in the `input` (refer search input), when we focus on it, we see a animations in border. Could you add similar to `textarea` as well.

2023-01-25 10:53 UTC, vedant-jain03 commented on app/views/commontator/comments/_form.html.erb
> +      form.text_area :body, rows: '3', id: new_record ?
```suggestion
      form.text_area :body, rows: '4', id: new_record ?
```

2023-01-25 13:47 UTC, Sauvic016 commented on app/views/commontator/comments/_form.html.erb
> +      form.text_area :body, rows: '3', id: new_record ?
Sure, I will make these changes asap.

2023-02-01 06:38 UTC, Sauvic016 commented
@vedant-jain03 could you review the changes once.

2023-02-09 11:52 UTC, Sauvic016 commented
@tachyons could you review the code.

2023-02-11 11:47 UTC, vedant-jain03 approved these changes

2023-02-11 11:50 UTC, merged