[revamp] : announcement UI
CircuitVerse/CircuitVerse pull request #3526
Opened 2023-01-25 16:30 UTC by vedant-jain03

Fixes #3525 

### Screenshots of the changes (If any) -

| ![Screenshot from 2023-01-25 21-56-28](https://user-images.githubusercontent.com/76901313/214619370-f96dfbb2-92fe-4e6a-8074-9a8e496c70b7.png) |
|-|
|New UI|

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-01-27 11:48 UTC, tachyons commented on app/controllers/application_controller.rb
> +    def set_announcement
Use current_announcement helper, no need to create additional methods

2023-01-30 10:45 UTC, vedant-jain03 commented
cc @tachyons

2023-01-30 12:58 UTC, tachyons requested changes

2023-01-30 12:58 UTC, tachyons commented on app/views/layouts/_header.html.erb
> +<nav class="<%= show_announcement %>">
You can simply keep existing css classes, and add navbar class conditionally, using a helper makes this code harder to understand

2023-01-31 13:53 UTC, tachyons commented on app/views/layouts/_header.html.erb
> +<nav class="<%= current_announcement ? 'navbar-announcement' : '' %> navbar navbar-expand-lg bg-white">
```suggestion
<nav class="<%= 'navbar-announcement'  if current_announcement %> navbar navbar-expand-lg bg-white">
```

2023-01-31 17:02 UTC, tachyons approved these changes

2023-01-31 17:07 UTC, merged