Solved: #3560 Error Message's text isn't aligned properly in Sign Up …
CircuitVerse/CircuitVerse pull request #3561
Opened 2023-02-12 17:18 UTC by MauryanKansara

Fixes #3560 

#### Describe the changes you have made in this PR -
Properly aligned the text of the Error Message in Sign Up page.

### Screenshots of the changes (If any) -

**Before:-**
![Screenshot (30)](https://user-images.githubusercontent.com/86093112/218326218-cab15080-2000-4a02-9603-3b1504dcaf87.png)

**After:-**
![Screenshot (32)](https://user-images.githubusercontent.com/86093112/218326247-f18dfc14-aa39-4cc8-9bfe-b97baef37c72.png)

2023-02-14 02:49 UTC, vedant-jain03 requested changes

2023-02-14 02:49 UTC, vedant-jain03 commented on app/views/users/registrations/new.html.erb
> +            <ul style="margin-bottom:0;">
do not use inline styling, try bootstrap class `mb-0`

2023-02-14 18:04 UTC, MauryanKansara commented
@vedant-jain03 can you please review my PR? I have made changes as you said, I used bootstrap class instead of inline CSS.

2023-03-30 05:12 UTC, MauryanKansara commented
> @vedant-jain03 can you please review my PR? I have made changes as you said, I used bootstrap class instead of inline CSS.

@vedant-jain03 can you review my changes pls?

2023-03-30 08:09 UTC, vedant-jain03 approved these changes
cc @tachyons

2023-04-02 10:39 UTC, MauryanKansara commented
> cc @tachyons

@tachyons can you merge my PR? The changes are already approved by Vedant.

2023-04-22 03:52 UTC, MauryanKansara commented
> > cc @tachyons
> 
> @tachyons can you merge my PR? The changes are already approved by Vedant.

@tachyons

2023-04-25 15:49 UTC, tachyons commented
MAster branch is currently broken, we need to get it fixed before merging new PRs

2026-05-25 16:15 UTC, closed without merging

2026-05-25 16:15 UTC, ShinichiShi commented
closing as the issue is resolved