feat: updated footer component
CircuitVerse/CircuitVerse pull request #3624
Opened 2023-02-27 19:13 UTC by thisiskaransgit

Fixes #3621 

#### Describe the changes you have made in this PR -
Removed Extra Space from the footer component

### Screenshots of the changes (If any) -

2023-03-02 10:30 UTC, vedant-jain03 commented
cc @Prerna-0202

2023-03-02 11:59 UTC, Prerna-0202 commented
After completely removing the extra space, the footer is looking like this. I think we can just decrease this space instead of removing the tag.
WDYT @vedant-jain03 @thisiskaransgit ?
![Screenshot (1202)](https://user-images.githubusercontent.com/89515816/222422193-a753a7bf-92c0-40a3-8ddc-9aba78e0ba83.png)

2023-03-02 20:37 UTC, thisiskaransgit commented
Hey @Prerna-0202, so rather than removing the whole container, I've reduced the size of it to 25px, hope this will suffice the need

2023-03-04 15:21 UTC, vedant-jain03 requested changes

2023-03-04 15:21 UTC, vedant-jain03 commented on app/assets/stylesheets/footer.scss
> +  height: 25px;
```suggestion
  height: 50px;
```

2025-02-06 14:44 UTC, VaibhavUpreti commented
Fixed via https://github.com/CircuitVerse/CircuitVerse/pull/5278

2025-02-06 14:44 UTC, closed without merging