adds a mentorship program section in about
CircuitVerse/CircuitVerse pull request #3661
Opened 2023-03-11 03:53 UTC by vikaskumar2703

Fixes #

#### Describe the changes you have made in this PR -
this pr adds a mentorship program section in about page of circuit verse main websites containing names and timeline of programs in which circuit verse has taken part as an organisation till date.
### Screenshots of the changes (If any) -

![Capture](https://user-images.githubusercontent.com/115652383/224463465-8d793384-09a3-415a-b52b-fb174f2a1855.PNG)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-03-13 04:00 UTC, vedant-jain03 requested changes
@vikaskumar2703 fix the codeclimate and hound issues!

2023-03-21 13:44 UTC, tachyons commented on app/views/about/index.html.erb
> +          </div>
Could you indent the html ?
```suggestion
          <div class="card-body">
            <p class=" fw-bolder mentorship-program-3"><%= t("about.mentorship_program_3") %></p>
            <p class="mentorship_program_time"><%= t("about.mentorship_program_3_timeline") %></p>
          </div>
```

2023-04-06 15:56 UTC, vedant-jain03 requested changes
@tachyons what if we place this section after core-team section or above it?

2023-04-06 15:59 UTC, vikaskumar2703 commented
> @tachyons what if we place this section after core-team section or above it?

above would be better option

2023-04-06 18:01 UTC, tachyons commented
> @tachyons what if we place this section after core-team section or above it?

Below the teams sections

2023-04-06 18:32 UTC, vedant-jain03 reviewed
@vikaskumar2703 Add some followup changes
Also, make this section below teams!

2023-04-06 18:32 UTC, vedant-jain03 commented on config/locales/views/about/en.yml
> +    program_gsod_timeline: "2023"
```suggestion
    program_gsod_timeline: "2020"
```

2023-04-06 18:32 UTC, vedant-jain03 commented on config/locales/views/about/en.yml
> +    mentorship_programs_heading: "MENTORSHIP PROGRAMS"
Add hindi translation as well, here: `config/locales/views/about/hi.yml`

2023-04-06 18:32 UTC, vedant-jain03 commented on config/locales/views/about/en.yml
> +    program_gsoc_timeline: "2020, 2021, 2022, 2023"
Make the years embed with respective program circuitverse page, for example : [2021](https://summerofcode.withgoogle.com/archive/2021/organizations/6293580166987776)

Note: you can make translation act as html by suffixing the key by `_html` for example `program_gsoc_timeline_html`

2023-04-17 10:39 UTC, vedant-jain03 requested changes
@vikaskumar2703 Any updates on changes?

2023-04-17 11:00 UTC, vikaskumar2703 commented
> @vikaskumar2703 Any updates on changes?

working on it . i have brought the mentorship section below core team but having some difficulty in translation and embeding the year thing.

2023-04-17 11:39 UTC, vikaskumar2703 commented
@vedant-jain03 
done with adding hindi translation as well 
only thing left is emedding years with links . can you pl share exactly what all links need to be embedded. That would be great help.

2023-04-17 12:11 UTC, vikaskumar2703 commented
> 
also what should be the most efficient way to embed the links because the idea in my mind is very complex

2023-04-21 06:59 UTC, vedant-jain03 approved these changes
@vikaskumar2703 Thanks for contribution, LGTM

cc @tachyons

2023-04-21 11:01 UTC, vikaskumar2703 commented
> @vikaskumar2703 Thanks for contribution, LGTM
> 
> cc @tachyons 

Pleasures all mine @vedant-jain03

2023-07-18 05:46 UTC, closed without merging