Integration testcases for profile
CircuitVerse/CircuitVerse pull request #3863
Opened 2023-07-02 13:06 UTC by tanmoysrt

#### Describe the changes you have made in this PR -
Test cases added for 
  - edit name
  - edit country
  - edit educational institute
  
Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-08-06 04:29 UTC, smritigarg commented
@tanmoysrt The PR looks good to me, just few suggestions for your consideration. Great work 😄

2023-08-11 16:46 UTC, smritigarg reviewed
Hi Thanks for the changes @tanmoysrt just some small feedback regarding test naming, otherwise looks good. I am approving the PR

2023-08-11 16:46 UTC, smritigarg approved these changes

2023-08-19 16:09 UTC, vedant-jain03 requested changes
Add test suit for localization as well, rest LGTM

2023-08-22 03:30 UTC, vedant-jain03 approved these changes

2023-08-22 03:43 UTC, merged