Change the implementation of the priority queue to use a heap data structure
CircuitVerse/CircuitVerse pull request #3916
Opened 2023-07-24 19:56 UTC by Prerna-0202

### **GSOC'23 TASK**

Fixes #103 

#### Describe the changes you have made in this PR -

 1. I have changed the implementation of the priority queue to use a heap data structure. Previously, it was using a linear data structure. 
Now, It is making use of a binary heap data structure to manage the priority queue. The add() method uses heapify-up to find the correct position for adding an element, and the remove() method uses heapify-down to maintain the heap property after removing an element. These heapify operations have logarithmic time complexity (O(log n)), which makes the binary heap implementation much more efficient for managing a priority queue compared to the linear implementation.
2. Now, as the time complexity reduces to (O(log n)) from (O(n)), I have changed the simulation queue limit to 100000.

Note: Please check **Allow edits from maintainers.** If you would like us to assist in the PR.

2023-08-27 10:29 UTC, gr455 requested changes
@Prerna-0202 nit: Can you change your naming of `this.frontIndex` to `this.backIndex`.
The front of the queue is where you pop elements from. In your case it seems you are popping from 0, so 0 is the frontIndex. You add elements through the back (although it doesnt matter in a PQ since even in the earlier implementation, the objs were being added from the front).

But yeah, naming it backIndex will be clearer in my opinion.

2023-08-27 10:40 UTC, gr455 commented
Everything else looks good! Great job with this

2023-08-27 10:59 UTC, gr455 commented
// @satu0king Please review

2023-08-27 11:02 UTC, gr455 commented on simulator/src/eventQueue.js
> +        while (true) {
Ignoring

2023-08-27 11:02 UTC, gr455 commented on simulator/src/eventQueue.js
> +            if (leftChildIndex < this.frontIndex && this.queue[leftChildIndex].queueProperties.time < this.queue[smallestChildIndex].queueProperties.time) {
Ignoring

2023-08-27 11:02 UTC, gr455 commented on simulator/src/eventQueue.js
> +            if (rightChildIndex < this.frontIndex && this.queue[rightChildIndex].queueProperties.time < this.queue[smallestChildIndex].queueProperties.time) {
Ignoring

2023-08-27 12:01 UTC, Prerna-0202 commented
> @Prerna-0202 nit: Can you change your naming of `this.frontIndex` to `this.backIndex`. The front of the queue is where you pop elements from. In your case it seems you are popping from 0, so 0 is the frontIndex. You add elements through the back (although it doesnt matter in a PQ since even in the earlier implementation, the objs were being added from the front).
> 
> But yeah, naming it backIndex will be clearer in my opinion.

yess, Done 👍

2023-09-03 17:32 UTC, satu0king approved these changes

2023-09-05 14:42 UTC, gr455 approved these changes

2023-09-05 16:12 UTC, merged