feat(gsoc): add feature flag for vue simulator
CircuitVerse/CircuitVerse pull request #4015
Opened 2023-09-05 07:45 UTC by Arnabdaz

Fixes #3768 

#### Describe the changes you have made in this PR -

- [ ] add vuesim feature flag for vue simulator
- [ ] add option to enable / disable simulator from user profile settings
- [ ] update simualtorcontroller to redirect to vue simualtor when feature flag is enabled 

### Screenshots of the changes (If any) -

N/A

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-09-05 14:05 UTC, vedant-jain03 approved these changes
LGTM 
cc @VaibhavUpreti check for delpoyement compatability

2023-09-05 17:56 UTC, VaibhavUpreti commented
Most of the things appear to be working correctly. I have a few questions @Arnabdaz :

1. Do we plan on merging #3797  before this PR? Without it, the simulator would not function and break the page for user, when viewing and launching(to edit) older circuits.

- I had tested these changes taking both PRs into account, then it works well.

2. Do developers need to clone the submodules when running the server? Is this the expected behaviour?

- If yes, we would have to update the documentation for cloning the submodule, installing all packages in `cv-frontend-vue` and then running bin/dev (probably can automate this later).

Else will give such error
```bash
22:39:51 js.1     | Error: package.json or package-lock.json is not found inside submodule directory
22:39:51 js.1     | error Command failed with exit code 1.
```

3. The project view modal seems to be broken, so if a user enables the vuesim then
- Multiple "view" button clicks trigger repeated page reconfirmation, 
- and the modal cannot load circuit data

![broken](https://github.com/CircuitVerse/CircuitVerse/assets/85568177/acb1b003-95df-47ec-8525-453803892935)

2023-09-05 18:43 UTC, Arnabdaz commented
@VaibhavUpreti 

1. no that pr won't be merged as the api endpoints were decided to be changed and move in projects controller at the gsoc second phase that pr is already merged but not deployed #3861 

2. yes the devs are intended to clone the repo with either `--recursive` as `git clone https://github.com/CircuitVerse/CircuitVerse.git --recursive' 
or,
they can clone the repo normally and then use 
`git submodule update --init` to clone the cv-frontend-vue repo (this would be updated in the setup.md files also)
the error is intentionally added as in future vue simulator would be the main and only simulator 
we can update the error message and add the part `run git submodule update --init to fix this issue` or something like that.

3. the embedded circuit can't be loaded as the prs are not yet merged in cv-frontend-vue repo once they are merged it would work and other issues should also be fixed

2023-09-07 11:11 UTC, VaibhavUpreti approved these changes
LGTM, cc @tachyons

2023-09-07 15:25 UTC, vedant-jain03 commented
> Could you please update the documentation for this in a follow up PR? @Arnabdaz

For this we need to good documentation, we need some checkpoints:
- [x] for contributors
- [x] a perfect setup
- [x] contribution for simulator and cv(rails)
- [x] contribution for simulator only(vue)
- [x] an ideal PR flow

etc....

2023-09-10 15:18 UTC, tachyons requested changes

2023-09-10 15:18 UTC, tachyons commented on app/views/users/circuitverse/edit.html.erb
> +          </div>
Make this text i18n compatiable, add a warning and move to a separate PR

2023-09-10 17:21 UTC, closed without merging