feat(github): github added to footer
CircuitVerse/CircuitVerse pull request #4041
Opened 2023-09-11 15:48 UTC by harshsharma-11

Fixes #4028 

#### Describe the changes you have made in this PR -
added a github repository link in footer 

### Screenshots of the changes (If any) -

![Screenshot (277)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/694279e5-06f2-4867-8c15-bcc48f6c1243)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-09-11 19:25 UTC, Arnabdaz requested changes
1. use the `/github` route instead of the actual url 
![image](https://github.com/CircuitVerse/CircuitVerse/assets/96580571/43fe7463-fd8f-405f-8a63-01795ec61cae)

2. Use a icon with transparent background.. ie, it should not have the white square edges and should be round edged

2023-09-11 19:25 UTC, Arnabdaz commented on app/views/layouts/_footer.html.erb
> +          <a class="bounce-out-on-hover" href="https://github.com/CircuitVerse" target="_blank" data-tooltip="github"><%= image_tag("logos/github-logo-square.jpg", class: "footer-social-icon pt-2", a
```suggestion
          <a class="bounce-out-on-hover" href="/github" target="_blank" data-tooltip="github"><%= image_tag("logos/github-logo-square.jpg", class: "footer-social-icon pt-2", alt: "GitHub Logo") %></a>
```

2023-09-11 22:30 UTC, tanmoysrt commented
@harshsharma-11 remove the background of github logo, as that will not look good in dark background

2023-09-12 02:45 UTC, harshsharma-11 commented on app/views/layouts/_footer.html.erb
> +          <a class="bounce-out-on-hover" href="https://github.com/CircuitVerse" target="_blank" data-tooltip="github"><%= image_tag("logos/github-logo-square.jpg", class: "footer-social-icon pt-2", a
okk let me make these changes

2023-09-12 03:15 UTC, harshsharma-11 commented on app/views/layouts/_footer.html.erb
> +          <a class="bounce-out-on-hover" href="https://github.com/CircuitVerse" target="_blank" data-tooltip="github"><%= image_tag("logos/github-logo-square.jpg", class: "footer-social-icon pt-2", a
@Arnabdaz done please check

2023-09-12 04:24 UTC, Arnabdaz approved these changes
LGTM 👍 

cc @tachyons

2023-09-12 04:24 UTC, Arnabdaz approved these changes

2023-09-14 02:55 UTC, harshsharma-11 commented
@tachyons please kindly review the pr as discuss in #4028

2023-09-14 04:17 UTC, tachyons requested changes
Please add logo with transparent background for consistency

2023-09-14 09:58 UTC, harshsharma-11 commented
cc@tachyons 
![Screenshot (287)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/b21f4b03-e9f7-43f2-aef4-5cd1783ab876)

2023-09-14 10:26 UTC, tanmoysrt commented
> cc @tachyons ![Screenshot (287)](https://user-images.githubusercontent.com/138685168/267937544-b21f4b03-e9f7-43f2-aef4-5cd1783ab876.png)

update this image in PR description as well

2023-09-15 05:49 UTC, Arnabdaz requested changes
@harshsharma-11 use logo from https://github.com/logos as current logo does not have a transparent background. else in future logo would have to be updated in case of change in footer color scheme

2023-09-15 06:20 UTC, harshsharma-11 commented
@tachyons @Arnabdaz please check i made bg transparent
![Screenshot (288)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/cdaffb8d-f440-4be5-8921-8f020160b094)

2023-09-21 17:53 UTC, merged