fix: Improve projects responsiveness#4108
CircuitVerse/CircuitVerse pull request #4131
Opened 2023-10-06 16:30 UTC by coldrohak

Fixes #

#### Describe the changes you have made in this PR -
Fixed the responsiveness of projects list page by containing the width of search-tags of projects and pagination overflow to scroll as in home page
### Screenshots of the changes (If any) -

![image](https://github.com/CircuitVerse/CircuitVerse/assets/105278343/87fd2eea-4b3f-4034-8e6c-181d3bbde4bd)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-10-07 14:00 UTC, coldrohak commented
Hey @tanmoysrt please review it

2023-10-07 16:25 UTC, tanmoysrt requested changes

2023-10-07 16:25 UTC, tanmoysrt commented on app/assets/stylesheets/components.scss
> +  overflow: scroll;
In mobile version, the overflow is likely to be solved. But in desktop there is a unnecessary scroll bar coming.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/33f75439-43f2-442a-ac30-508fc9329451)

I think, you can switch to `overflow: auto`, that may solve the issue

2023-10-07 19:50 UTC, coldrohak commented
@tanmoysrt yeah, now it doesn't 
![circuitVersepr1](https://github.com/CircuitVerse/CircuitVerse/assets/105278343/b20e14e7-4966-4ba0-aabe-1181193b1184)

2023-10-08 06:50 UTC, tanmoysrt approved these changes
In mobile and desktop, the issues seems to be fixed !

cc @vedant-jain03

2023-10-09 15:59 UTC, vedant-jain03 approved these changes

2023-10-09 17:58 UTC, merged

2023-12-04 19:47 UTC, tachyons commented
<img width="1134" alt="Screenshot 2023-12-05 at 1 17 20 AM" src="https://github.com/CircuitVerse/CircuitVerse/assets/3112976/021819f2-6f61-438a-9983-eacb3afd2bfa">
This broke the tags on profile, reverting