fix: alignment of name for searched profiles
CircuitVerse/CircuitVerse pull request #4143
Opened 2023-10-07 09:30 UTC by niladrix719

Fixes #4142

#### Describe the changes you have made in this PR -

removed a div which wraps the user name and profile picture as a row

### Screenshots of the changes (If any) -

![Screenshot 2023-10-07 at 2 59 06 PM](https://github.com/CircuitVerse/CircuitVerse/assets/91966855/2adfc771-6b8c-43a2-8a42-9fefc50cb8da)

2023-10-07 09:31 UTC, niladrix719 commented
cc @vedant-jain03

2023-10-09 15:27 UTC, vedant-jain03 requested changes

2023-10-09 15:27 UTC, vedant-jain03 commented on app/views/users/circuitverse/search.html.erb
> +          <p class=" center-row search-username"><%= profile.name %></p>
Better to place under div, we can give class; `flex flex-col` so that it appears in expected way

2023-10-09 17:49 UTC, niladrix719 commented
cc @vedant-jain03

2023-10-12 13:08 UTC, niladrix719 commented
cc @tanmoysrt

2023-10-12 15:26 UTC, tanmoysrt approved these changes
Working as expected!

2023-10-15 08:31 UTC, vedant-jain03 approved these changes

2023-10-15 08:38 UTC, merged