fixes responsiveness
CircuitVerse/CircuitVerse pull request #4151
Opened 2023-10-07 17:10 UTC by Malavi1

Fixes #4110

#### Describe the changes you have made in this PR -
I just fixed the media queries of the 3 buttons.

2023-10-07 19:14 UTC, niladrix719 requested changes

2023-10-07 19:14 UTC, niladrix719 commented on app/assets/stylesheets/home.scss
>    }
add space here after line 68

2023-10-12 05:18 UTC, Malavi1 commented
@tachyons could you please review my PR

2023-10-15 11:34 UTC, tanmoysrt commented
@Malavi1 this seems to be ready for merging. Fix the code climate issue.

2023-10-20 10:03 UTC, Malavi1 commented
@tanmoysrt  could you please help me with this

2023-10-20 10:13 UTC, tanmoysrt commented
> @tanmoysrt  could you please help me with this

Fix the codeclimate issue

2023-10-25 15:59 UTC, tanmoysrt commented
Hi @Malavi1 can you resolve the code climate issues?

2023-10-26 08:57 UTC, Malavi1 commented
Yes I did but after also I am getting this error. 
Could you please help me with this?

2023-10-26 09:11 UTC, Malavi1 commented
> hi @Malavi1 line no. 69 is containing a space can you please remove it, i think that will fix the code climate issue

As for the flow it needs a white space right?

2023-10-26 09:18 UTC, niladrix719 commented
@Malavi1 the code climate issue still persists, you will need to add the vertical space between the function declarations and also make sure there is no space horizontally on line no. 69

2023-10-26 09:46 UTC, niladrix719 approved these changes

2023-10-26 09:48 UTC, Malavi1 commented
@tanmoysrt review it once

2023-10-27 10:31 UTC, tanmoysrt approved these changes
Looks good !
cc @vedant-jain03

2023-11-14 13:07 UTC, merged