Merge pull request #1 from CircuitVerse/master
CircuitVerse/CircuitVerse pull request #4185
Opened 2023-10-15 11:16 UTC by shakthi2003-ice

Fixed #4167

Fixes #

#### Describe the changes you have made in this PR -
I have integrated LookBook in Viewcomponent

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-10-15 11:22 UTC, tanmoysrt commented
@shakthi2003-ice Please provide a valid PR title and description.
And you must be assigned to the issue before raising any PR.

Please follow that next time, also get assigned yourself to the issue first before reviewing.

2023-10-15 11:26 UTC, shakthi2003-ice commented
]

2023-10-15 11:27 UTC, shakthi2003-ice commented
@tanmoysrt I already requested to assign me this issue as it has not been assigned to anyone. But I didn't get any response so i started working on the issue. Extremely sorry. Will make sure that it won't happen again

2023-11-07 06:24 UTC, tachyons commented
Could you add at least one component on this page? https://github.com/CircuitVerse/CircuitVerse/tree/master/app/component

2023-11-07 06:42 UTC, shakthi2003-ice commented
> Could you add at least one component on this page? https://github.com/CircuitVerse/CircuitVerse/tree/master/app/component

@tachyons sure

2023-11-20 10:12 UTC, niladrix719 requested changes

2023-11-20 10:12 UTC, niladrix719 commented on Gemfile
> +group :development do
there is already a `group :development do` here: https://github.com/CircuitVerse/CircuitVerse/blob/0762999968fc96c632edd6a3fe5beca776b8c416/Gemfile#L154
you could have added the gem there

2023-11-20 10:12 UTC, niladrix719 commented on config/routes.rb
> +Rails.application.routes.draw do
there is already a `Rails.application.routes.draw do` here: https://github.com/CircuitVerse/CircuitVerse/blob/0762999968fc96c632edd6a3fe5beca776b8c416/config/routes.rb#L4, you can add it here

2023-11-20 10:28 UTC, niladrix719 commented
@shakthi2003-ice i think the gem "actioncable" is also missing, can you make it so that you can Enable live UI updates on the components - https://github.com/CircuitVerse/CircuitVerse/tree/master/app/component

2024-01-04 10:52 UTC, closed without merging