Enhanced user experience by integrating a color picker
CircuitVerse/CircuitVerse pull request #4262
Opened 2023-11-09 14:38 UTC by shauryag2002

Fixes #4227 

#### Describe the changes you have made in this PR -
Simplified user interaction by implementing a color picker for seamless navigation and effortless selection of vibrant colors.
### Video of the Feature -

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/213a2b9b-3b05-4bda-80f7-83a338a2dc87

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-11-09 14:48 UTC, shauryag2002 commented on app/component/project_embed_component.html.erb
> +            <input type="color" class="w-25 h-auto" id="color_picker">
@tanmoysrt Can you tell me , What I exactly need to add for this accesslint (bot) issue ?

2023-11-12 13:21 UTC, tanmoysrt requested changes
Hi @shauryag2002 
The color picker is working fine.

There is an issue.
Suppose user  has updated colour hex code from the input box, then you should also sync with the colour picker so that always the colour representing by color picker and hex code in textbox is same

2023-11-13 13:06 UTC, vedant-jain03 requested changes

2023-11-13 13:06 UTC, vedant-jain03 commented on app/component/project_embed_component.html.erb
> +  });
```suggestion
  color_picker.addEventListener('input', function() {
      colorDisplay.value = color_picker.value;
  });
  document.getElementById('border_color').addEventListener('input', (e) => {
    color_picker.value = e.target.value
  })
```

Thanks for this. LGTM
We can make it dynamic through `input` event listener

2023-11-13 16:33 UTC, vedant-jain03 approved these changes
Thanks for the changes @shauryag2002 🚀

2023-11-20 07:03 UTC, tanmoysrt approved these changes
Looks good !
Thanks @shauryag2002

2023-11-20 07:07 UTC, merged