fix: enable add member and add mentor button upon single email entry
CircuitVerse/CircuitVerse pull request #4268
Opened 2023-11-13 09:32 UTC by niladrix719

Fixes #4256

#### Describe the changes you have made in this PR -

1. fix enable add member and add mentor button upon single email entry
2. Corrected the classname for mentor button which was previous an id

### Screenshots of the changes (If any) -

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/c8a0dac3-1952-4580-a260-547734a9e0d0

2023-11-13 10:29 UTC, niladrix719 commented
cc @tanmoysrt

2023-11-19 06:18 UTC, tanmoysrt requested changes

2023-11-19 06:18 UTC, tanmoysrt commented on app/views/groups/_add_mentor_modal.html.erb
> +            <%= form.submit "Add mentors", class: "btn primary-button add-mentor-button" %>
Instead of making `add-mentor-button` and `add-member-button` as class name, keep it as ID because it signifies a single element only

2023-12-14 04:20 UTC, tanmoysrt approved these changes
Looks good :+1:

2023-12-14 04:24 UTC, merged