feat(ui): improve login-signup page ui
CircuitVerse/CircuitVerse pull request #4311
Opened 2023-11-24 10:27 UTC by theslowdeveloper

Fixes #4092 

#### Describe the changes you have made in this PR -
[Screencast from 23-11-23 11:05:24 PM IST.webm](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/4c7f35f8-f39d-4c89-80ac-78a72bdc2bb7)

### Screenshots of the changes (If any) -
![Screenshot from 2023-11-24 15-55-19](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/60708c9b-cc9e-42f0-b630-f55765f7fdb7)

![Screenshot from 2023-11-24 15-55-26](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/9397cbb7-d5f5-4c12-b191-0a4d7f9870b2)

![Screenshot from 2023-11-24 15-56-50](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/81c37918-9a4f-4260-92c0-2c2864eecb15)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-11-24 14:41 UTC, theslowdeveloper commented
@tachyons do you know why this test is failing 
Ruby on Rails CI / test (pull_request) ?

2023-11-24 15:06 UTC, tachyons commented
@theslowdeveloper It is related to the changes you made. It is failing because test unable to find login button. You can run those tests in your machine to validate.

2023-11-28 12:54 UTC, theslowdeveloper commented
> @theslowdeveloper It is related to the changes you made. It is failing because test unable to find login button. You can run those tests in your machine to validate.

I updated the text of login button which was causing the issue so update the test for it.

2024-01-08 06:42 UTC, nitin10s requested changes
Hey, this looks good. Just one small problem with the smaller screen design size. It says "Continue with" which makes the whole sentence - Login with "continue with". Can we keep the button name the same as it is for the larger screens [Google, etc]

2024-01-24 17:01 UTC, senbo1 commented
Hello @nitin10s, Fixed the issues for smaller screen sizes, the text remains same for all screen size. Please have a review when you are free.

https://github.com/CircuitVerse/CircuitVerse/assets/102225113/d1546553-cb76-45e0-8a21-fc0d1c537d2d

2024-02-03 14:08 UTC, senbo1 commented
Done @tanmoysrt

2024-02-24 12:40 UTC, tanmoysrt approved these changes
Looks nice !
Great work @senbo1 :rocket:

2025-08-31 15:56 UTC, closed without merging