feat(dashboard): revamp the search input #3379
CircuitVerse/CircuitVerse pull request #4381
Opened 2023-12-15 15:10 UTC by nisha-laur

Fixes #
This pull request addresses the "Revamp: Search Input in Dashboard #3379" issue in CircuitVerse. 

#### Describe the changes you have made in this PR -
It aims to improve the search input appearance in the dashboard making it look more appealing by modifying some css code and adding the class 'form-control' and  'form-input' .  

### Screenshots of the changes (If any) -
A) When Input tag is not clicked and selected 
Before :
<img width="904" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/104618576/a846ba02-6c0c-4dee-ad6b-c4b64958f3fa">

After:
<img width="874" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/104618576/2e755751-314e-4c82-a167-5051490081d0">

B)A) When Input tag is  clicked and selected 
Before: It shows plain black color which clearly does not matches with the website theme .
<img width="905" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/104618576/5aaf7ef6-6575-466a-9de2-e8f69c6b0fc7">
After:
<img width="891" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/104618576/2a31986d-a4dc-47d3-a235-a0048cdb8523">

2023-12-16 03:07 UTC, tanmoysrt commented
Hi @nisha-laur 
Thanks for raising the PR.

As per the code of conduct, you must get assigned to the issue before raising the PR.
As you are first-time contributor and none is assigned to that issue, comment there #3379, and I will assign the issue to you.

From the next contributions, follow the flow.

2023-12-16 03:30 UTC, nisha-laur commented
Thank you, I will do that.

On Sat, 16 Dec, 2023, 8:37 am Tanmoy Sarkar, ***@***.***>
wrote:

> Hi @nisha-laur <https://github.com/nisha-laur>
> Thanks for raising the PR.
>
> As per the code of conduct, you must get assigned to the issue before
> raising the PR.
> As you are first-time contributor and none is assigned to that issue,
> comment there #3379
> <https://github.com/CircuitVerse/CircuitVerse/issues/3379>, and I will
> assign the issue to you.
>
> From the next contributions, follow the flow.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CircuitVerse/CircuitVerse/pull/4381#issuecomment-1858695281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY6FUUB44OJDDKRF7PU6T2TYJUGALAVCNFSM6AAAAABAWSZ6FKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJYGY4TKMRYGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-16 08:07 UTC, tanmoysrt commented on app/assets/stylesheets/users.scss
> +    // border-left: 1px solid $form-border-grey;
```suggestion
```

2023-12-16 08:09 UTC, tanmoysrt requested changes

2023-12-16 08:09 UTC, tanmoysrt commented on app/assets/stylesheets/users.scss
> +    border: 1px solid #42b983;
Use the defined variables, don't use direct hex code for color

2023-12-16 08:09 UTC, tanmoysrt commented on app/assets/stylesheets/users.scss
> +      border-color: green;
Use the defined variables, don't use direct hex code for color

2023-12-16 08:09 UTC, tanmoysrt commented on app/assets/stylesheets/users.scss
> +
remove blank space

2023-12-16 08:09 UTC, tanmoysrt commented on app/assets/stylesheets/users.scss
> +
remove blank space

2023-12-17 02:41 UTC, tanmoysrt approved these changes
Looks Good !

2023-12-17 02:45 UTC, merged