Feat: Migrating Delete comment confirmation modal partial  to a view component
CircuitVerse/CircuitVerse pull request #4457
Opened 2023-12-30 05:20 UTC by DhairyaMajmudar

Fixes #4170 

#### Describe the changes you have made in this PR -
Migrating the Delete comment confirmation modal partial to a view component 

### Screenshots of the changes (If any) -

![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/0d773176-6264-495b-806f-58ac904bd684)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2023-12-30 17:41 UTC, DhairyaMajmudar commented
@tanmoysrt @tachyons pls. take a look

Thank you : )

2023-12-31 17:13 UTC, niladrix719 reviewed
the delete_comment component controller file seems to be empty

2023-12-31 17:33 UTC, DhairyaMajmudar commented
The controllers file is empty since this component doesn't contain any controller logic.

2024-01-05 06:34 UTC, DhairyaMajmudar commented
@tachyons @tanmoysrt pls. review.

2024-01-05 09:33 UTC, DhairyaMajmudar commented
@niladrix719 @tanmoysrt pls .review and merge

2024-01-05 09:47 UTC, tachyons commented on app/component/delete_comment_confirmation_modal_component.rb
Empty file ?

2024-01-05 09:51 UTC, DhairyaMajmudar commented on app/component/delete_comment_confirmation_modal_component.rb
Yes it was created while running the command the. Shall I delete this ?

2024-01-07 16:24 UTC, DhairyaMajmudar commented on app/component/delete_comment_confirmation_modal_component.rb
I have added the controllers in the empty file.

2024-01-09 04:09 UTC, tachyons requested changes
Good start,

- Add the button which triggers the modal to view component
- Add related JS file to the view component
- Add component preview and make sure that preview is working fine in lookbook
- Check if this can be extracted to generic delete modal which can be re-used.

2026-05-28 18:55 UTC, naman79820 commented
stale pr

2026-05-28 18:55 UTC, closed without merging