feat(change password): Implemented a change password feature
CircuitVerse/CircuitVerse pull request #4483
Opened 2024-01-01 07:53 UTC by Miran-Firdausi

Fixes #4465 

#### Describe the changes you have made in this PR -
I have implemented a change password feature with three inputs current password, new password, and confirm password. also i have added all the new words into all the langauges. I have also tested the working in different scenarios
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-01-02 18:13 UTC, tanmoysrt commented
Hi @Miran-Firdausi can you write testcases for this ?

2024-01-03 10:15 UTC, Miran-Firdausi commented
@tanmoysrt If you can assist me on how to do that. I would love to do it.

2024-01-03 10:42 UTC, tanmoysrt commented
> @tanmoysrt If you can assist me on how to do that. I would love to do it.

You can checkout this blog to understand Rspec > https://www.theodinproject.com/lessons/ruby-introduction-to-rspec

you can check this testcases that how to write for your changes > https://github.com/CircuitVerse/CircuitVerse/blob/master/spec/controllers/users_circuitverse_controller_spec.rb

2024-02-24 13:43 UTC, tanmoysrt requested changes
Hi @Miran-Firdausi
The implementation looks good !

Few changes required - 
1. Use primary button, green background with white text like other part to keep to the theme.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/e7fface0-76aa-45c9-80c5-b769c2b93cea)
2. For all the text (for response, message) you have used, make those i18n compaitable.
3. Instead of seperate page, if you can use a model that may be better.
4. You need to add testcases for `update_password` method

2026-05-28 19:18 UTC, naman79820 commented
stale pr

2026-05-28 19:18 UTC, closed without merging