Fixed_responsiveness
CircuitVerse/CircuitVerse pull request #4500
Opened 2024-01-03 06:35 UTC by deepak05kr18

Fixes # https://github.com/CircuitVerse/CircuitVerse/issues/4448

- Implemented responsiveness for smaller screens using media queries:
  - For screens with a maximum width of 768px, reduced the font size to 10px.
  - For screens with a maximum width of 500px, further reduced the font size to 8px.

<img width="245" alt="Screenshot 2024-01-03 120356" src="https://github.com/CircuitVerse/CircuitVerse/assets/122279122/04bc2fc0-c6be-455a-8946-29afe206d199">

2024-01-03 15:46 UTC, deepak05kr18 commented
@tanmoysrt , I did the required changes please review it.

2024-01-06 14:03 UTC, tanmoysrt commented
Hi @deepak05kr18 fix the title of pull request.
Will review once the Rails CI fixed.

2024-01-06 14:39 UTC, deepak05kr18 commented
> Hi @deepak05kr18 fix the title of pull request. Will review once the Rails CI fixed.

Done @tanmoysrt

2024-01-28 14:40 UTC, tanmoysrt requested changes
It's not a font size related issue.

Better fix will be to make the textarea take 100% width of modal instead of `cols` parameter which is not responsive at all.

2024-01-28 16:50 UTC, deepak05kr18 commented
> It's not a font size related issue only.
> 
> Better fix will be to make the textarea take 100% width of modal instead of `cols` parameter which is not responsive at all.

Sure, will work on it.

2026-05-28 19:17 UTC, naman79820 commented
stale pr

2026-05-28 19:17 UTC, closed without merging