fix(simulator) : fixes the username display in simulator
CircuitVerse/CircuitVerse pull request #4514
Opened 2024-01-04 15:42 UTC by aryanndwi123

Fixes #

#### Describe the changes you have made in this PR -
Username of the person was not visible when simulator screen minimized

### Screenshots of the changes (If any) -

Before changes:
![0](https://github.com/CircuitVerse/CircuitVerse/assets/100300789/1a8c8ad1-e6d3-4416-86c0-668da41495b9)

After changes:
![1](https://github.com/CircuitVerse/CircuitVerse/assets/100300789/909fe3d7-04a9-4984-8c1a-6952d160b470)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-01-04 17:06 UTC, aryanndwi123 commented
Hi @Prerna-0202 @Arnabdaz ,
Can you review this pr and tell me the required changes.

2024-01-05 11:37 UTC, Arnabdaz commented
please link the issue for which this fix is.

2024-01-05 11:52 UTC, aryanndwi123 commented
> please link the issue for which this fix is.
Sure @Arnabdaz 
I have linked it..!

2024-01-08 20:26 UTC, tanmoysrt requested changes

2024-01-08 20:26 UTC, tanmoysrt commented on simulator/src/css/main.stylesheet.css
> +
Instead of removing use
`margin-right: auto`

2024-01-28 14:58 UTC, tanmoysrt commented on simulator/src/css/main.stylesheet.css
> +
```suggestion
```

2024-01-28 14:59 UTC, tanmoysrt approved these changes
Looks good :+1:

2024-01-28 15:04 UTC, merged