fix: paragraph style missing in contribution page
CircuitVerse/CircuitVerse pull request #4607
Opened 2024-01-16 07:14 UTC by ManeetChhabra

Fixes #4601 

#### Describe the changes you have made in this PR -
center aligned text on contribution page from justified.

### Screenshots of the changes (If any) -

![image](https://github.com/CircuitVerse/CircuitVerse/assets/130479331/1d8bbbb8-e4be-47d7-8924-6b40b4a63491)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-01-16 07:17 UTC, ManeetChhabra commented
@Malavi1 @tanmoysrt have a look...

2024-01-16 19:20 UTC, amananand20 commented
hey @ManeetChhabra, you can even use bootstrap class(text-center) to make text align center as bootstrap is being used in this project.

2024-01-16 20:38 UTC, tanmoysrt requested changes

2024-01-16 20:38 UTC, tanmoysrt commented on app/assets/stylesheets/contribute.scss
> +
the class name should be like `centered-paragraph`, as it has property `text-align: center`

2024-01-17 11:05 UTC, ManeetChhabra commented
@tanmoysrt sir, i made the required changes.

2024-01-28 15:37 UTC, tanmoysrt approved these changes
Working as expected :+1: 
Good job @ManeetChhabra

2024-01-28 15:42 UTC, merged

2024-01-28 16:06 UTC, ManeetChhabra commented
> Working as expected 👍 Good job @ManeetChhabra

Thanks @tanmoysrt !!