Update in CONTRIBUTING.md "pending triage"
CircuitVerse/CircuitVerse pull request #4614
Opened 2024-01-17 07:13 UTC by foad-khan

Fixes #

#### Describe the changes you have made in this PR -
>updated "pending triage" in - CONTRIBUTING.md file

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-01-17 12:41 UTC, beingnoble03 commented on CONTRIBUTING.md
> +- [pending triage](https://github.com/CircuitVerse/CircuitVerse/labels/pending%20triage)
I guess the label description should be in the same line.

2024-01-28 15:40 UTC, tanmoysrt requested changes

2024-01-28 15:40 UTC, tanmoysrt commented on CONTRIBUTING.md
> +labeled issues are not verified by maintainers.
```suggestion
- [pending triage](https://github.com/CircuitVerse/CircuitVerse/labels/pending%20triage) labeled issues are not verified by maintainers.
```

2024-01-28 15:41 UTC, tanmoysrt approved these changes
Looks good :+1:

2024-01-28 15:48 UTC, merged