chore: fix typos
CircuitVerse/CircuitVerse pull request #4689
Opened 2024-02-06 18:05 UTC by Kiran-pande-30

Fixes #4676

#### Describe the changes you have made in this PR -
Updated the Small Typo Error

### Screenshots of the changes  -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-03-07 05:47 UTC, tanmoysrt requested changes

2024-03-07 05:47 UTC, tanmoysrt commented on config/locales/views/announcements/en.yml
> +    no_announcement_heading: "No Announcements so far."
old one is correct

2024-03-07 05:47 UTC, tanmoysrt commented on config/locales/views/featured_circuits/en.yml
> +    main_description: "These circuits have been hand-picked by our Authors for their awesomeness"
old one is correct

2024-03-07 11:36 UTC, Kiran-pande-30 commented
Are the necessary changes updated ? It's taking time in codespaces to update the changes

2024-10-09 11:01 UTC, keshavagr273 commented
@tanmoysrt hey could you pls assign me this issue. I would love to work on this.

2025-02-27 20:07 UTC, ThatDeparted2061 commented
Hey @Kiran-pande-30 I see you have been  a  bit active recently on the org,
So would  you like to also make changes to the Add members under Add mentors ? Or if rebasing the branch is too much of a  hassle I could give issue to someone else ?

2026-05-28 19:15 UTC, naman79820 commented
stale pr

2026-05-28 19:15 UTC, closed without merging