fix: scrolling position fixed
CircuitVerse/CircuitVerse pull request #4711
Opened 2024-02-09 17:10 UTC by Pradipram

Fixes #4710 

#### Describe the changes you have made in this PR -
I have fixed this issue. Now, it is scrolling to the correct position.

### Screenshots of the changes (If any) -
[Screencast from 09-02-24 10:13:01 PM IST.webm](https://github.com/CircuitVerse/CircuitVerse/assets/101059602/bda2c716-4c69-4160-80f1-428616c64ad0)

2024-03-07 06:04 UTC, tanmoysrt requested changes

2024-03-07 06:04 UTC, tanmoysrt commented on app/views/layouts/_header.html.erb
> +        <a class="nav-link navbar-item navbar-text <%= request.path == "/features" ? "active" : "" %>" href="/#home-features-section" onclick="event.preventDefault(); window.scrollTo({ top: document.
Not a correct approach to resolve this.

You should add `scroll-margin-top: 100px` instead.

2024-03-07 18:47 UTC, Pradipram commented
@tanmoysrt, I have made some changes. Please have a look into this.

2024-05-31 22:04 UTC, tanmoysrt approved these changes
:+1: Looks good !

Thank you @Pradipram for your contribution.

2024-05-31 22:07 UTC, merged