fix(notifications): fix the notifications margin bug
CircuitVerse/CircuitVerse pull request #4741
Opened 2024-02-18 05:30 UTC by yuvrajsingh176

Fixes #4535

#### Describe the changes you have made in this PR -
There was a bug in the div with id "all-notifications-div" which had mb-10 and the "unread-notifications-div" had mb-3. I made the "all-notifications-div" margin bottom to  mb-3 which resolved the bug. 

### Screenshots of the changes (If any) -

https://github.com/CircuitVerse/CircuitVerse/assets/74402961/777c71b7-973a-449d-a4fc-11892d0ca870
before 

https://github.com/CircuitVerse/CircuitVerse/assets/74402961/e34b259e-3c7b-424c-9774-402d7e3f0061
After

Note: Please check **Allow edits from maintainers.** If you would like us to assist in the PR.

2024-02-22 16:32 UTC, vedant-jain03 requested changes

2024-02-22 16:32 UTC, vedant-jain03 commented on app/views/users/noticed_notifications/index.html.erb
> +  <div id="all-notifications-div" class="d-flex flex-column bd-highlight mb-3 mt-3 notifications_container">
```suggestion
  <div id="all-notifications-div" class="d-flex flex-column bd-highlight my-3 notifications_container">
```

2024-02-22 16:46 UTC, yuvrajsingh176 commented on app/views/users/noticed_notifications/index.html.erb
> +  <div id="all-notifications-div" class="d-flex flex-column bd-highlight mb-3 mt-3 notifications_container">
Changed mb-3 mt-3 to my-3.

2024-02-25 07:10 UTC, vedant-jain03 commented
@yuvrajsingh176 Could you please resolve the conflicts?

2024-02-25 07:39 UTC, vedant-jain03 approved these changes

2024-02-29 05:12 UTC, richardshaju commented
@yuvrajsingh176 Why changes on `package-lock.json`?

2024-02-29 05:16 UTC, yuvrajsingh176 commented
> @yuvrajsingh176 Why changes on `package-lock.json`?

I was getting failed on one check in lint so i tried doing npm install and pushed the code so it has changes in package-lock.json.

2024-02-29 05:44 UTC, richardshaju commented
@yuvrajsingh176 Revert the changes in `package-lock.json`

2024-02-29 05:55 UTC, yuvrajsingh176 commented
> @yuvrajsingh176 Revert the changes in `package-lock.json`

Reverted

2024-05-31 22:16 UTC, tanmoysrt commented on app/assets/stylesheets/users.scss
> +border-radius: 4px;
Can you please fix the formatting.

2026-05-28 19:14 UTC, naman79820 commented
stale pr

2026-05-28 19:14 UTC, closed without merging